### ISSUE TITLE
How about increasing the number of playouts to 1600?

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#251] opened 2017-12-04 19:27 UTC
Reason 1: There is no particular reason not to follow the value from the AGZ paper. Though DeepMind didn't mention in the paper what has led them to that specific value, I believe that they must have done some benchmarks around it.

Reason 2: After seeing [this table](https://github.com/gcp/leela-zero/pull/238#issuecomment-348858737), I feel like 1600 is more a stable value under other parameter changes. Of course that was just a specific case and things should be tested, but still.

Reason 3: The winrate prediction commented on the games in [this reddit post](https://www.reddit.com/r/cbaduk/comments/7hiise/leela_zero_585k_network_beats_beginerbot_twice/) left me an impression that its value net is better than its policy net in terms of quality. In other words, current LZ recognized when a bad move is played but a bad policy net does not notice it is a bad move before it being played. Again this argument is not based on extensive experiments and is just an impression, of course.

Reason 4: I think we can afford a 37.5% decrease in self-play speed now, since it seems like the training/evaluation part is the bottleneck for me. We are not clearly training a new network (and corresponding checkpoints) every 25k games.

**Comment by sethtroisi** [comment] 2017-12-04 19:38
More on Reason 4: Newer nets and recent code changes have dramatically increased game speed, [see graphs here](https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/edit#gid=0) looks like a 40% increase from shorter games and next branch will be >30%* faster and hasn't been released. This is a form of ["Playing with House Money"](https://www.investopedia.com/terms/h/house-money-effect.asp).

*speeds ups [10% here](https://github.com/gcp/leela-zero/commit/171cd59a4bb6930729db6f617283d6ff24d6d8d3), [10% here](https://github.com/gcp/leela-zero/commit/8a01db302b7b5f7ee7f52322f050b053832c8c46), [more % here](https://github.com/gcp/leela-zero/commit/30657866ab005f5cae103d0f7db76e593c340f95), [more optimizations](https://github.com/gcp/leela-zero/commit/fdb23d778e181ec20a34d4faa4e006d637422572)

**Comment by evanroberts85** [comment] 2017-12-04 21:00
I am in favour of this though. We could do a test, 61% of self play games at 1000 playouts, 39% of games at 1,600 playouts. Use all the games to train the next version (so nothing is lost) but train also two networks, the first with only with the new 1,600 playout games, the second with just the 1,000 playout games, and have a match between these two networks.

**Comment by gcp** [comment] 2017-12-05 09:55
In principle I have nothing against this but it remains a completely arbitrary value. Why not 2000, 3200, ... ?

**Comment by isty2e** [comment] 2017-12-05 09:58
@gcp After all LZ tries to replicate AGZ, so why not this one? Also as written in the Reason 1, I believe the specific value was determined by some sort of optimization, though it might be a crude one. There was no reason to use 1000 playouts either at the first place.

**Comment by gcp** [comment] 2017-12-05 10:06
Fair argument.

I think for the next release we will have:
a) 1600 playouts
b) resigning in 80% of games at 5% winrate
c) pile of speedups for the engine
d) potentially different fpu/Q(s, a) + PUCT settings

If we change (d) we might as well change (a).

**Comment by evanroberts85** [comment] 2017-12-05 10:09
For each network you could do a test with 10% higher and 10% lower no. of playouts (with a reverse proportion of games played) , the next network is trained using whichever value wins. This way you will eventually settle on the optimal number.

**Comment by isty2e** [comment] 2017-12-05 10:18
@gcp Ugh, I'm not getting what your intention is exactly. Do you mean that it will be changed from 1600 once the MCTS settings are settled?

@evanroberts85 In principle more playouts is desirable in terms of Elo rating gain/games. So what we really have to measure is Elo rating gain/time, but it becomes complicated if you consider how training is done practically. We're basically training a new NN per day or two, so again it is impossible to measure that quantity in the current situation unless training is fully automated so that a new net will be out every 25k games. The last thing to consider is that Elo rating does not increase linearly over time so such an optimization might take a long time.

**Comment by evanroberts85** [comment] 2017-12-05 10:33
@inbae I suggested that the self play games with lower and higher playouts
are done simultaneously, with the training for the higher playout games
compensated by using a lower number of games, so the computation time is
equal. This requires much more training and testing of course and writing
new code to automate, so may not be practical at the moment but it is what
you would do if you wanted to find the optimal number and not just guess.

**Comment by isty2e** [comment] 2017-12-05 10:36
@evanroberts85 I'm a bit dubious if we really need to find out a value other than 1600 considering the time and efforts to be dedicated to it, but who knows, it may worth it.

**Comment by marcocalignano** [comment] 2017-12-05 10:50
With the new autogtp under development you could change this and other options without the need of a new release

**Comment by evanroberts85** [comment] 2017-12-05 11:24
If we move to 1600 playouts (and I agree we should) then we need to do a test at 1600 vs 1000 to see what jump in elo this is giving us, otherwise the graph will be inaccurate.

**Comment by gcp** [comment] 2017-12-05 11:32
The graph compares networks, so the amount of playouts doesn't matter for it.

**Comment by gcp** [comment] 2017-12-05 11:37
>Ugh, I'm not getting what your intention is exactly. Do you mean that it will be changed from 1600 once the MCTS settings are settled?

I am saying I'm OK to take this in the next release but I want to clarify the FPU/MCTS issue before making that, as it has potentially a big impact.

**Comment by isty2e** [comment] 2017-12-05 11:38
Okay, I understood.

**Comment by evanroberts85** [comment] 2017-12-05 11:57
The graph starts at random play (which gains nothing from increased
playouts), so if the first network test against this random network had
been at 1600 playouts the elo gain would have been slightly higher. We
missed out on this by starting testing on just 1000 playouts.

**Comment by isty2e** [comment] 2017-12-05 12:00
I think the current rating estimation is very inaccurate already, so I wonder whether it would matter. AGZ ratings are also recalibrated by anchors, otherwise the ratings become odd because of self-bias.

**Comment by gcp** [comment] 2017-12-06 07:54
...and the next iteration of AGZ did it with 800 playouts. They removed the "proportional play at the root", though.

**Comment by isty2e** [comment] 2017-12-06 07:58
Things become more confusing after AlphaZero... But still other points remain somewhat valid, I think.

**Comment by isty2e** [comment] 2017-12-06 08:01
My speculation is that they needed to balance the training and self-play speed, so this is accomplished with more TPUs and less playouts. Of course there's no evidence for it, but they're missing too much of technical details.

**Comment by evanroberts85** [comment] 2017-12-06 10:25
Note that the 800 playouts was designed to be good across all three games,
there are considerably less possible moves per position in chess than go,
so those 800 playouts allow the chess and shogi programmes to look much
deeper.

**Comment by gcp** [comment] 2017-12-06 19:10
That's a fair point, but it shows that 800 obviously still works for go.

**Comment by evanroberts85** [comment] 2017-12-06 21:53
I think it would be as big as a mistake to assume 800 is optimal due to Deepmind now using that number, as is was before to assume 1600 was just because AlphaGo used it. They are two different projects with different code, ours is a third. 

We know the level of the policy network is way more important than the number of playouts to a programmes playing strength, so if you were confident of inproving the policy network quickly then you would not worry about reducing the number of playouts, I think this is what Deepmind did after the changes to training and other paramaters.

**Closed** 2017-12-07 09:39 UTC
