### ISSUE TITLE
Proposal: Validity verification for contributing autogtp / leelaz.exe

### ISSUE THREAD

**Issue by jokkebk** [gcp/leela-zero#1790] opened 2018-08-29 17:17 UTC
There seem to be several cases of misconfigured (let's assume not malicious) clients contributing training games and possibly match games. Could we have a "test suite" for self-compiled autogtp/leela executables before they are allowed to contribute? For example something like this:

1) Client computes it's SHA checksum and sends to server
2) Checksum compared against "known good" checksums of binaries
3) If a match is found, no further testing (assume non-malicious users)
4) If no match is found, run a "test game" for that network with pregiven seed, for example "generate 100 moves with 80 visits and return SHA hash of the moves"
5) If test game checksum matches one produced by "known good" executable, add new checksum to "known good" database

With a new network, we could accumulate test checksums for a couple of games, or just go with blind luck and assume the first returned challenge is the correct one.

Or is this too much work for probably a small issue? Or would it be better to randomly cross-check submitted games, as this would catch also malicious users?

**Comment by MartinDevelopment** [comment] 2018-08-29 17:27
Step 1 wouldn't work because you can just edit the code to send a valid checksum.

**Comment by kuba97531** [comment] 2018-08-29 18:10
I think it's too complicated and something much simpler should be used to detect non-malicious errors. The bottom line should be that the default for personal builds of autogtp and leelaz should not be able to send games to the official server.
And as MartinDevelopment has stated your solution is just too easy to work-around for malicious agents.

**Comment by tterava** [comment] 2018-08-29 22:12
Only known way to find out if a game is valid is to replay the game from the start with same parameters as the client we are trying to validate. You can't even check moves in the middle of the game without calculating the entire game because you don't know the state of the tree at that point.

If a malicious attackers wants to make an undetectable client that sends bad data it's actually very easy to do so, unless we spend 50% (or more) processing power to replay all the games that are sent. Most non-malicious clients are pretty easy to spot but lately there have been cases where it's quite obvious the attack is done on purpose, like that one client sending old pro games. Replaying those games would quite quickly show them as fake but if we started checking only the start of every game, a smart attacker would just place the fake moves at the end of the games.

**Comment by Nazgand** [comment] 2018-08-30 14:52
If the previous computation was thrown away every move, and the only random numbers used were pseudo-random numbers, then any move in the game could be `verified' at only the cost of the computation of a single move. The calculated game tree should be exactly the same, and the move must correspond with the game tree&training data. 1 move may not be enough if the play style too closely matches LeelaZero's(it may even be LeelaZero vs DataPollutingHuman), so perhaps 3 moves of each color could be verified.

If the calculated game tree & training data still do not match, to would because threads racing each other producing data that affect other threads in non-trivial ways. This could be dealt with by recording the calculation process more thoroughly, reducing communication between threads, or having threads wait for other threads. If the calculation process is not recorded, then all timing issues must be dealt with; e.g. threads must do exactly the amount of work planned, not doing extra when waiting for other threads or less when some deadline is reached.

**Comment by alreadydone** [comment] 2018-08-30 16:01
Self-play games for training uses one thread only. The problem is that floating point calculations produce different results on different GPU/operating system/maybe compiler. Look for "reproducibility" in the early issues.

**Comment by tterava** [comment] 2018-08-30 16:46
@Nazgand 
Throwing away previous tree state every turn would result in a lot of duplicate processing and weaker gameplay. Validation would be fast, but now you're consuming massive amounts of processing power during self play and match games. Instead of fixing the issue you're just moving it around.

**Comment by Marcin1960** [comment] 2018-08-31 12:05
What about non-open verification code in form of an obfuscated/encrypted dll library?

**Comment by gcp** [comment] 2018-09-03 11:12
Dozens of issues already filed about why 99% of what is proposed here can't work at all.

**Closed by gcp** 2018-09-03 11:12 UTC
Labels: duplicate
