### ISSUE TITLE
Behavior Leelaz 0.16 and Gogui

### ISSUE THREAD

**Issue by qzq1** [gcp/leela-zero#2003] opened 2018-11-07 15:28 UTC

**Comment by qzq1** [comment] 2018-11-07 15:38
I ran a set of games between LZ188 and LZ157 using gogui, with 100 visits and 600 visits respectively, approximating time parity, using leelaz 0.16 for the first time, and got some odd results.  Most games took about an hour, which is typical on my cpu machine, but 8 of 32 games were duplicates of others, and these took less than a minute each, according to gogui output data.  With a number of previous 40B/15B matches using leelaz 0.15 using the same settings, I've never seen duplicate games.

**Comment by alreadydone** [comment] 2018-11-07 16:10
At low visit counts the NNCache from the beginning of the game can be kept till the end of the game, and can be reused by a later game, since gogui doesn't restart leelaz after each game. When this happens the game will be very fast and become a duplicate of the earlier game. 0.16 instroduced symmetry detection in NNCache, so it's more likely to get cache hits. You may also want to check if there are games not exactly identical but differ only by a symmetry.

**Comment by qzq1** [comment] 2018-11-07 16:34
I understand.  Thanks for the explanation.

**Comment by Friday9i** [comment] 2018-11-07 19:30
I noticed the same, but using -t 2 or -t 3 solves the issue in most of the cases 
To avoid duplicates, I also use -n and -m 20 (or 50) coupled with --randomvisits with generally 10% of the visits (10 and 60 in your case) to avoid random play of very bad moves.

**Comment by pliuphys** [comment] 2018-11-07 20:10
I encountered this problem before with 0.15 and 1600 visits. It would be nice to have a driver that can restart the engine, and do a fixed number of games.

**Comment by qzq1** [comment] 2018-11-08 01:48
@Friday9i that’s really helpful. Thanks!

**Comment by l1t1** [comment] 2018-11-08 02:14
does random play means chose of all valid moves, or chose from some better moves?

**Comment by Friday9i** [comment] 2018-11-09 07:08
@l1t1 Parameter -m 50 generate totally random moves from time to time for the first 50 moves, but I
add --randomvisits xyz, with xyz being the minimum number of visits the random has received: hence, random moves are "not too random", they are among moves that received at least xyz visits. Generally I put xyz = 10% of the number of visits (for 1600 visits, I use --randomvisits 160) to get some random play but quite strong (because weak moves don't receive 160 visits!).
For low visits, there's a difficulty: 10% of 3 visits for example is 0.3 visits, lol, so I use --randomvisits 1. And I use -t 3 or -t 4 as I noticed it avoids (most of) duplicate games (and without it, I can get over 90% of duplicate games for -v 1, which is a problem!).

**Comment by Vandertic** [comment] 2018-11-09 07:35
Actually parameter -m XX ask the engine to choose the firs XX moves randomly, but not with equal probability: with probability proportional to the number of visits. Hence if the "best" move got 150 visits over a total of 300 it will have 1/2 probability. Moves with 5 visits will have 1/30 probability and so on.
This does not guarantees that a fairly good move will be typically chosen, as in many situations there will be a lot of bad moves with few visits that added together have a high probability.
This can be adjusted with a not too known option which is --randomtemp X. (X a positive real number, default 1.)
This "temperature" changes the proportionality relation between visits and probability. If the temperature is 0, the move with the most visits is chosen with probability 1. If the temperature is infinite (say, in the limit), all visited moves have equal probability regardless of visits number. 
You can play with this parameter and see what happens. My suggestion is that a value around 0.5-0.7 should be low enough to get rid of low visits moves in a smooth way, while still giving the agent some randomness.

**Closed** 2018-11-15 11:02 UTC
Labels: techsupport
