### ISSUE TITLE
Release 0.14 - Verification Failed?

### ISSUE THREAD

**Issue by odeint** [gcp/leela-zero#1328] opened 2018-05-04 21:58 UTC
I was just checking out the new binary release (leela-zero-0.14-win64), and got a match as the first job. On the upload it printed an error but kept going with the next match game. I haven't seen this before, but also haven't always saved and checked the logs, so maybe it is not related to the new release. It might also just be a server issue, not a client one. Can @roy7 perhaps check this?

Update: Second match also failed verification in the same way, full log extended.
Update 2: Third match did succeed, full log extended. I found it on the server website as well, http://zero.sjeng.org/viewmatch/264bda9b923806c85c1675a7e8876de7ce6a07861326d3e3ed2571a2c95f23b8?viewer=wgo . The two failed ones are not there.
Update 3: I can't actually find the string "Verification failed" in our codebase with the Github search, so I'm not sure what triggers this message.
Update 4: The games that it played do look weird, opened them in an sgf viewer now. Opening is normal but then it becomes strange. Is the ELF-compatibility stuff now always on, even for normal LZ operation? So autogtp should not be used?
[kifu.zip](https://github.com/gcp/leela-zero/files/1976056/kifu.zip)

> Uploading match: 536bbc7bb8684ff2976b64643b091418.sgf for networks ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199 and d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323
> Verification failed.1 game(s) (0 self played and 1 matches) played in 10 minutes = 642 seconds/game, 3867 ms/move, last game took 620 seconds.

<details>
 <summary>Full Log</summary>
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\patro\Downloads\leela-zero-0.14-win64>autogtp.exe -k kifu
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: networks/ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199
net: ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199.
./leelaz --tune-only -w networks/ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199
Using 2 thread(s).
RNG seed: 8730476316144245744
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1060 6GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 391.01
Device speed:  1847 MHz
Device cores:  10 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1060 6GB
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1444 ms (816.7 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1238 ms (953.0 GFLOPS)
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1158 ms (1018.5 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0927 ms (1272.0 GFLOPS)
(8/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0833 ms (1416.8 GFLOPS)
(125/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0806 ms (1463.4 GFLOPS)
(127/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0738 ms (1597.9 GFLOPS)
(137/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0692 ms (1704.1 GFLOPS)
(170/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0670 ms (1760.2 GFLOPS)
(264/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0666 ms (1771.5 GFLOPS)
(282/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0643 ms (1835.9 GFLOPS)
Tuning process finished
Starting thread 1 on GPU 0
{
    "black_hash": "ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199",
    "cmd": "match",
    "leelaz_version": "0.13",
    "options": {
        "noise": "false",
        "playouts": "0",
        "randomcnt": "0",
        "resignation_percent": "5",
        "visits": "3200"
    },
    "options_hash": "0ebb2fca5c4f07aa1cc5a9a4c1c84361c0412572eb55df8a2f9c82f7afe8f9f95bbdd1",
    "random_seed": "10519016969163213352",
    "required_client_version": "15",
    "white_hash": "d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323"
}

Got new job: match
Net filename: networks/d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323
first network: ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199.
second network d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323.
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
1 (B R16) 2 (W D4) 3 (B C3) 4 (W D3) 5 (B C4) 6 (W C6) 7 (B C5) 8 (W D5) 9 (B B6) 10 (W D16) 11 (B Q3) 12 (W P17) 13 (B Q14) 14 (W R5) 15 (B O4) 16 (W C2) 17 (B B2) 18 (W B7) 19 (B D2) 20 (W D7) 21 (B E6) 22 (W D6) 23 (B E2) 24 (W R8) 25 (B C14) 26 (W C15) 27 (B D14) 28 (W F16) 29 (B C10) 30 (W B5) 31 (B B4) 32 (W C12) 33 (B D12) 34 (W B12) 35 (B E10) 36 (W B14) 37 (B F8) 38 (W G4) 39 (B G6) 40 (W A6) 41 (B F4) 42 (W M3) 43 (B C8) 44 (W F7) 45 (B G7) 46 (W F5) 47 (B G5) 48 (W F3) 49 (B H4) 50 (W G3) 51 (B H3) 52 (W E8) 53 (B F9) 54 (W F6) 55 (B E3) 56 (W D11) 57 (B E4) 58 (W D10) 59 (B D9) 60 (W E9) 61 (B E5) 62 (W F10) 63 (B E11) 64 (W C11) 65 (B B15) 66 (W B16) 67 (B F11) 68 (W O2) 69 (B Q5) 70 (W R4) 71 (B Q4) 72 (W M5) 73 (B R3) 74 (W R11) 75 (B L4) 76 (W M4) 77 (B L3) 78 (W M7) 79 (B M2) 80 (W N2) 81 (B L2) 82 (W R7) 83 (B P7) 84 (W M9) 85 (B Q9) 86 (W S10) 87 (B Q17) 88 (W L17) 89 (B K16) 90 (W L16) 91 (B K15) 92 (W P16) 93 (B R13) 94 (W L15) 95 (B K14) 96 (W O5) 97 (B N6) 98 (W M6) 99 (B K17) 100 (W M13) 101 (B L12) 102 (W M12) 103 (B L11) 104 (W M11) 105 (B N5) 106 (W L10) 107 (B D8) 108 (W E7) 109 (B B8) 110 (W A4) 111 (B C1) 112 (W G10) 113 (B H9) 114 (W G12) 115 (B F13) 116 (W A8) 117 (B C7) 118 (W B6) 119 (B A9) 120 (W G13) 121 (B A7) 122 (W Q18) 123 (B A5) 124 (W S17) 125 (B R18) 126 (W R17) 127 (B Q16) 128 (W S18) 129 (B P18) 130 (W R19) 131 (B P15) 132 (W P13) 133 (B O16) 134 (W O17) 135 (B N17) 136 (W O18) 137 (B N18) 138 (W P19) 139 (B N15) 140 (W K18) 141 (B P14) 142 (W O14) 143 (B O13) 144 (W O12) 145 (B S16) 146 (W S12) 147 (B S13) 148 (W T16) 149 (B O15) 150 (W N13) 151 (B L14) 152 (W M14) 153 (B M15) 154 (W L18) 155 (B J18) 156 (W H18) 157 (B J19) 158 (W J17) 159 (B H17) 160 (W J16) 161 (B G18) 162 (W H16) 163 (B G17) 164 (W L13) 165 (B M16) 166 (W resign) Game has ended.
Score: B+Resign
Winner: black
Uploading match: 536bbc7bb8684ff2976b64643b091418.sgf for networks ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199 and d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323
Verification failed.1 game(s) (0 self played and 1 matches) played in 10 minutes = 642 seconds/game, 3867 ms/move, last game took 620 seconds.
{
    "black_hash": "d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323",
    "cmd": "match",
    "leelaz_version": "0.13",
    "options": {
        "noise": "false",
        "playouts": "0",
        "randomcnt": "0",
        "resignation_percent": "5",
        "visits": "3200"
    },
    "options_hash": "0ebb2f0b1b0c588801eff791a1a1c0ec877f98d8e27b4b5bf33a08cb70dd500aa5a0fc",
    "random_seed": "14550952934559187849",
    "required_client_version": "15",
    "white_hash": "ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199"
}

Got new job: match
first network: d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323.
second network ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199.
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
1 (B Q17) 2 (W D4) 3 (B C3) 4 (W C4) 5 (B D3) 6 (W F3) 7 (B E3) 8 (W E4) 9 (B F2) 10 (W Q4) 11 (B C16) 12 (W R15) 13 (B O16) 14 (W E17) 15 (B D14) 16 (W B3) 17 (B B2) 18 (W G2) 19 (B B4) 20 (W G4) 21 (B B5) 22 (W E2) 23 (B D2) 24 (W H17) 25 (B F5) 26 (W F4) 27 (B O3) 28 (W P3) 29 (B O4) 30 (W Q6) 31 (B K3) 32 (W M3) 33 (B M4) 34 (W L4) 35 (B L3) 36 (W M5) 37 (B N4) 38 (W K4) 39 (B M2) 40 (W J4) 41 (B R8) 42 (W R10) 43 (B S5) 44 (W O2) 45 (B N2) 46 (W R5) 47 (B S6) 48 (W S4) 49 (B S3) 50 (W T3) 51 (B R12) 52 (W P10) 53 (B Q14) 54 (W R14) 55 (B R13) 56 (W R17) 57 (B R18) 58 (W S18) 59 (B R16) 60 (W S17) 61 (B S16) 62 (W Q18) 63 (B Q16) 64 (W Q9) 65 (B P18) 66 (W R19) 67 (B D17) 68 (W E18) 69 (B D11) 70 (W L17) 71 (B E8) 72 (W C9) 73 (B D9) 74 (W C11) 75 (B C10) 76 (W B10) 77 (B D10) 78 (W B12) 79 (B B9) 80 (W D12) 81 (B C13) 82 (W C12) 83 (B E12) 84 (W C8) 85 (B B8) 86 (W B14) 87 (B E13) 88 (W C14) 89 (B D13) 90 (W B13) 91 (B E16) 92 (W A11) 93 (B F16) 94 (W D18) 95 (B J17) 96 (W J16) 97 (B H16) 98 (W H15) 99 (B H18) 1100 (W G17) 101 (B K16) 102 (W G16) 1103 (B K17) 104 (W K15) 105 (B L16) 106 (W L15) 107 (B J14) 108 (W J15) 109 (B G18) 110 (W F17) 111 (B M16) 112 (W C7) 113 (B P19) 114 (W F14) 115 (B F15) 116 (W F11) 117 (B E11) 118 (W G13) 119 (B Q19) 120 (W G15) 121 (B E14) 122 (W C15) 123 (B D15) 124 (W C17) 125 (B D16) 126 (W G8) 127 (B F10) 128 (W G10) 129 (B G11) 130 (W H11) 131 (B F12) 132 (W O6) 133 (B S10) 134 (W S9) 135 (B S11) 136 (W R9) 137 (B G9) 138 (W P2) 139 (B H10) 140 (W B7) 141 (B B16) 142 (W F1) 143 (B C18) 144 (W D1) 145 (B A3) 146 (W B1) 147 (B D6) 148 (W J11) 149 (B K9) 150 (W N14) 151 (B L11) 152 (W L12) 153 (B M12) 154 (W L13) 155 (B K11) 156 (W K12) 157 (B N8) 158 (W C6) 159 (B C5) 160 (W D5) 161 (B A6) 162 (W P17) 163 (B P16) 164 (W O17) 165 (B R18) 166 (W N17) 167 (B Q18) 168 (W N16) 169 (B N15) 170 (W M15) 171 (B O15) 172 (W L18) 173 (B M17) 174 (W M18) 175 (B J18) 176 (W N18) 177 (B K19) 178 (W F18) 179 (B L19) 180 (W G19) 181 (B N19) 182 (W H19) 183 (B M19) 184 (W F19) 185 (B J19) 186 (W J10) 187 (B A7) 188 (W A8) 189 (B A9) 190 (W J9) 191 (B O11) 192 (W N9) 193 (B N10) 194 (W M9) 195 (B L9) 196 (W P12) 197 (B O13) 198 (W O12) 199 (B N12) 200 (W O10) 201 (B N13) 202 (W P13) 203 (B P14) 204 (W M14) 205 (B O14) 206 (W M10) 207 (B M11) 208 (W A10) 209 (B A8) 210 (W C2) 211 (B B3) 212 (W resign) Game has ended.
Score: B+Resign
Winner: black
Uploading match: 981a60610a00436eabdd8f66a04b781a.sgf for networks d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323 and ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199
Verification failed.2 game(s) (0 self played and 2 matches) played in 22 minutes = 672 seconds/game, 3558 ms/move, last game took 700 seconds.
{
    "black_hash": "d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323",
    "cmd": "match",
    "leelaz_version": "0.13",
    "options": {
        "noise": "false",
        "playouts": "0",
        "randomcnt": "0",
        "resignation_percent": "5",
        "visits": "3200"
    },
    "options_hash": "0ebb2f9b0beaf1b6cd1a12b9feae65f55438c3db815c66579466024ebfcc669b878df8",
    "random_seed": "3008980087407294969",
    "required_client_version": "15",
    "white_hash": "ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199"
}

Got new job: match
first network: d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323.
second network ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199.
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
1 (B C16) 2 (W Q4) 3 (B R3) 4 (W R4) 5 (B Q3) 6 (W O3) 7 (B P3) 8 (W P4) 9 (B O2) 10 (W D4) 11 (B R16) 12 (W E17) 13 (B D14) 14 (W P17) 15 (B C3) 16 (W C4) 17 (B D3) 18 (W E3) 19 (B E2) 20 (W F2) 21 (B F3) 22 (W E4) 23 (B G2) 24 (W D2) 25 (B F1) 26 (W C2) 27 (B Q14) 28 (W N2) 29 (B N3) 30 (W O4) 31 (B M2) 32 (W S3) 33 (B N1) 34 (W R2) 35 (B Q2) 36 (W Q1) 37 (B P2) 38 (W R12) 39 (B S5) 40 (W S4) 41 (B R9) 42 (W P13) 43 (B R6) 44 (W P7) 45 (B P9)
46 (W Q16) 47 (B R15) 48 (W P14) 49 (B Q18) 50 (W Q8) 51 (B S10) 52 (W Q15) 53 (B Q17) 54 (W R14) 55 (B P16) 56 (W P15) 57 (B S14) 58 (W Q13) 59 (B O16) 60 (W R17) 61 (B S17) 62 (W P18) 63 (B R18) 64 (W N17) 65 (B G17) 66 (W J17) 67 (B G15) 68 (W J15) 69 (B M5) 70 (W C12) 71 (B C10) 72 (W E12) 73 (B E16) 74 (W E10) 75 (B C8) 76 (W E8) 77 (B D11) 78 (W D12) 79 (B E11) 80 (W F11) 81 (B F12) 82 (W B9) 83 (B D10) 84 (W B10) 85 (B E9) 86 (W G11) 87 (B D8) 88 (W F8) 89 (B F9) 90 (W G9) 91 (B F10) 92 (W G10) 93 (B G8) 94 (W C9) 95 (B D9) 96 (W B8) 97 (B E6) 98 (W F7) 99 (B C6) 100 (W H8) 101 (B B13) 102 (W B12) 103 (B F13) 104 (W B7) 105 (B F5) 106 (W H6) 107 (B B6) 108 (W B5) 109 (B A7) 110 (W F4) 111 (B C7) 112 (W F16) 113 (B E15) 114 (W F17) 115 (B G16) 116 (W F14) 117 (B F15) 118 (W E13) 119 (B G14) 120 (W E14) 121 (B H12) 122 (W B14) 123 (B C14) 124 (W C13) 125 (B B15) 126 (W A13) 127 (B G4) 128 (W J13) 129 (B J12) 130 (W H13) 131 (B G13) 132 (W K12) 133 (B K11) 134 (W L12) 135 (B J7) 136 (W K9) 137 (B G7) 138 (W H7) 139 (B G6) 140 (W H5) 141 (B L11) 142 (W G5) 143 (B F6) 144 (W M11) 145 (B H4) 146 (W K5) 147 (B J4) 148 (W M6) 149 (B N5) 150 (W N6) 151 (B J5) 152 (W J6) 153 (B H9) 154 (W S11) 155 (B R8) 156 (W Q6) 157 (B R7) 158 (W R5) 159 (B T5) 160 (W H10) 161 (B K6) 162 (W J8) 163 (B L6) 164 (W L7) 165 (B L5) 166 (W G12) 167 (B K7) 168 (W L8) 169 (B H18) 170 (W J18) 171 (B O10) 172 (W N9) 173 (B Q9) 174 (W R10) 175 (B T10) 176 (W B17) 177 (B D18) 178 (W A15) 179 (B A16) 180 (W A14) 181 (B B16) 182 (W N11) 183 (B S13) 184 (W T11) 185 (B Q10) 186 (W R11) 187 (B S8) 188 (W S2) 189 (B N8) 190 (W M9) 191 (B O5) 192 (W T4) 193 (B S6) 194 (W O8) 195 (B P5) 196 (W O6) 197 (B P6) 198 (W Q7) 199 (B Q5) 200 (W T2) 201 (B B3) 202 (W B2) 203 (B O9) 204 (W M7) 205 (B D1) 206 (W B4) 207 (B B1) 208 (W A3) 209 (B J16) 210 (W K16) 211 (B C1) 212 (W A5) 213 (B K8) 214 (W J9) 215 (B O7) 216 (W N7) 217 (B P19) 218 (W O18) 219 (B J19) 220 (W K19) 221 (B H19) 222 (W K18) 223 (B A6) 224 (W H17) 225 (B G18) 226 (W H16) 227 (B P11) 228 (W P12) 229 (B O11) 230 (W O12) 231 (B A8) 232 (W N4) 233 (B A9) 234 (W A11) 235 (B M4) 236 (W R13) 237 (B P1) 238 (W R1) 239 (B N10) 240 (W M10) 241 (B H14) 242 (W J14) 243 (B O19) 244 (W N19) 245 (B Q19) 246 (W D5) 247 (B D6) 248 (W T13) 249 (B T14) 250 (W Q11) 251 (B S15) 252 (W T12) 253 (B C11) 254 (W B11) 255 (B P8) 256 (W O7) 257 (B D13) 258 (W A1) 259 (B E1) 260 (W A10) 261 (B A2) 262 (W M3) 263 (B L3) 264 (W A1) 265 (B C5) 266 (W S12) 267 (B A2) 268 (W G3) 269 (B H3) 270 (W A1) 271 (B L9) 272 (W M8) 273 (B A2) 274 (W G1) 275 (B H1) 276 (W A1) 277 (B N18) 278 (W M18) 279 (B A2) 280 (W S9) 281 (B T9) 282 (W A1) 283 (B M19) 284 (W N18) 285 (B A2) 286 (W T8) 287 (B T7) 288 (W A1) 289 (B E5) 290 (W H15) 291 (B A2) 292 (W D15) 293 (B C15) 294 (W A1) 295 (B J10) 296 (W A2) 297 (B K4) 298 (W L10) 299 (B E7) 300 (W J11) 301 (B D16) 302 (W K10) 303 (B F18) 304 (W H11) 305 (B D17) 306 (W O15) 307 (B resign) Game has ended.
Score: W+Resign
Winner: white
Uploading match: bc80b7101e0b45429154081aa241e0b5.sgf for networks d987c1c92bbb01969d557e87c0ec61d552e2555fd756f884dda3f175c7425323 and ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199
Match data 264bda9b923806c85c1675a7e8876de7ce6a07861326d3e3ed2571a2c95f23b8 stored in database
3 game(s) (0 self played and 3 matches) played in 37 minutes = 747 seconds/game, 3274 ms/move, last game took 894 seconds.
{
    "cmd": "selfplay",
    "hash": "ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199",
    "leelaz_version": "0.13",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "30",
        "resignation_percent": "5",
        "visits": "3201"
    },
    "options_hash": "cb9add",
    "random_seed": "13223950762452213494",
    "required_client_version": "15"
}

Got new job: selfplay
net: ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199.
Engine has started.
Infinite thinking time set.
1 (B D16) 2 (W C4) 3 (B R4) 4 (W Q16) 5 (B R17)
</details>

**Comment by l1t1** [comment] 2018-05-04 22:32
Verification failed means the sgf maybe modified manually?

**Comment by gcp** [comment] 2018-05-04 22:32
>Is the ELF-compatibility stuff now always on, even for normal LZ operation?

It detects the type of weights from the weights file.

**Comment by gcp** [comment] 2018-05-04 22:32
This is a sever issue FWIW.

**Comment by Mardak** [comment] 2018-05-04 23:10
@roy7 confirmed that the server's secret does indeed generate those options_hash:
```
 "options_hash": "0ebb2fca5c4f07aa1cc5a9a4c1c84361c0412572eb55df8a2f9c82f7afe8f9f95bbdd1",
 "options_hash": "0ebb2f0b1b0c588801eff791a1a1c0ec877f98d8e27b4b5bf33a08cb70dd500aa5a0fc",
 "options_hash": "0ebb2f9b0beaf1b6cd1a12b9feae65f55438c3db815c66579466024ebfcc669b878df8",
```

There's additional logging on the server now to log what the client ends up sending back: https://github.com/gcp/leela-zero-server/pull/80

**Comment by Mardak** [comment] 2018-05-04 23:27
This should be fixed with https://github.com/gcp/leela-zero-server/pull/82

**Comment by Mardak** [comment] 2018-05-04 23:29
If anyone was curious…
```
require("mongodb").Long.fromString("10519016969163213352").toString()
'-7927727104546338264'
require("mongodb").Long.fromString("14550952934559187849").toString()
'-3895791139150363767'
require("mongodb").Long.fromString("3008980087407294969").toString()
'3008980087407294969'
```

First 2 matches became signed mismatch.

**Closed** 2018-05-04 23:29 UTC
Labels: bug

**Comment by odeint** [comment] 2018-05-04 23:31
Very good, thanks! Btw I also searched the server Github for the string "Verification Failed" but came up empty. Where is that actual line of code?

**Comment by Mardak** [comment] 2018-05-04 23:33
It's because the server often runs off of `next` instead of `master`:

https://github.com/gcp/leela-zero-server/blob/next/server.js#L579

(hint hint @roy7 ;) )

**Comment by Mardak** [comment] 2018-05-04 23:37
There we go, `next` merged into `master`, and search finds it now:

https://github.com/gcp/leela-zero-server/search?q=Verification+failed.

**Comment by odeint** [comment] 2018-05-04 23:44
I didn't actually know Github behaves that way, I thought it would always search all branches or the active one that the user clicked before. Seems not so, only way to search would be to clone to the own machine instead of the website. Kind of a strange design decision by Github IMHO, but ¯\_(ツ)_/¯

https://stackoverflow.com/questions/31891733/searching-code-in-a-specific-github-branch
