### ISSUE TITLE
Leela Zero vs Golaxy  

### ISSUE THREAD

**Issue by KID1412999** [gcp/leela-zero#1204] opened 2018-04-14 10:55 UTC
http://portal.yikeweiqi.com/online/golive/detail?id=8326

**Comment by roy7** [comment] 2018-04-14 12:38
Leela makes a crazy suicide move with a win rate 35% below the best move Lizzie reported. People think it's the search tree max size bug again perhaps.

**Comment by tterava** [comment] 2018-04-14 12:49
Is there a link for second game or is there a break?

**Comment by roy7** [comment] 2018-04-14 12:50
@tterava It's one game per day all week. So game #2 same time tomorrow.

**Comment by billyswong** [comment] 2018-04-14 12:51
This 1st game ended by B+Time. There must be some bug, whatever that bug is for LeelaZero to timeout.

**Comment by hydrogenpi** [comment] 2018-04-14 12:55
where are the logs?

**Comment by roy7** [comment] 2018-04-14 12:56
It wasn't a timeout really. LZ played a suicide move, then apparently resigned after Golaxy's next move.

**Comment by tterava** [comment] 2018-04-14 12:56
After B: F2 the evaluation dropped to less than 5%. I think LZ missed the killing move.

**Comment by roy7** [comment] 2018-04-14 12:58
For historical record (until Twitch deletes it) here was my Lizzie stream with no preparation, lol. https://www.twitch.tv/videos/250227472

White's J19 should never have been played. I don't see how it's possible outside of a bug.

**Comment by rchs819** [comment] 2018-04-14 12:59
Last commentary from http://portal.yikeweiqi.com/online/golive/detail?id=8318

> 坏小子：黑超时胜 据现场消息，是连线器的出错导致了150手巨勺的发生。不然正常下的话，LZ自评是39%的胜率，虽然稍差，但是也不是不可以搏一搏的。前期黑棋两个三三起手，颇有点针对LZ的意思在里面，毕竟LZ更倾向于地沟的，结果黑棋刚上来就把下水道给堵住了，白棋没得掏了。之后中腹的作战眼花缭乱，以黑棋得分而告终，之后白棋就陷入被动，直至刚刚连线器出错，直接爆炸。。。左下角特地咨询了下老中医，只是黑棋搜刮一圈的结果，并没有死活问题。恭喜星阵先下一城，期待明天第二局的开战，双方一共是七番棋，明天是蘑菇大哥为大家带来直播，敬请期待！

**Translated**
Bad boy: Black overtime victory According to the on-site news, it was the error of the connector that led to the occurrence of 150 hands. Otherwise, LZ self-evaluation is 39% winning rate, although slightly worse, but it is not a fight. The two black and three hands of the early black game are quite a bit to the meaning of LZ. After all, LZ is more inclined to trench. As a result, Black just blocked the sewer and White did not succeed. After that, the battle in the belly was dazzled and ended with black scores. White then fell into a passive state until the connector had just made a mistake and exploded. . . The lower left corner specifically consulted the old Chinese medicine practitioners. It was just the result of black crickets smashing the lap. There was no question of life and death. Congratulations to the Star Wars advance to the next city and look forward to the start of the second inning tomorrow. The two sides will have a total of seven games. Tomorrow is the mushroom brother who brings live broadcasts for everyone. Stay tuned!

**Comment by fohristiwhirl** [comment] 2018-04-14 13:01
> it was the error of the connector

Does that mean a misclick?

**Comment by roy7** [comment] 2018-04-14 13:03
Gotta love machine translation of Chinese. :)

When it says "error of the connector" was it a misclick by the operator if the games are being hand-relayed into the client?

**Comment by Splee99** [comment] 2018-04-14 13:33
It's hard to win from 39% winrate.

**Comment by tterava** [comment] 2018-04-14 13:38
> As a result, Black just blocked the sewer and White did not succeed. After that, the battle in the belly was dazzled and ended with black scores. White then fell into a passive state until the connector had just made a mistake and exploded. . .

Sounds epic.

**Comment by roy7** [comment] 2018-04-14 13:38
@bood Thanks. If someone can reproduce a pondering / time control bug maybe we can get it fixed then?

**Comment by tterava** [comment] 2018-04-14 13:45
@roy7 On the master branch what happens with pondering is that it throws away the tree and it can't be reused on LZ's turn. LZ then uses NNCache to quickly recalculcate all the results it did during pondering, but this completely messes up n/s calculation which also affects time control. In addition with large trees, all those memory operations can put serious delay at the start of the turn before time control even begins. It might take 10+ seconds before thinking starts, further messing up the time control (at least those are the results I had with my setup). I would imagine the issue is even greater with hardware that can build way bigger trees than usual setups, leading to more memory ops.

If this is the issue then it's already fixed in next branch. It only required one line of code to instruct LZ to keep the tree after pondering is finished.

**Comment by hydrogenpi** [comment] 2018-04-14 14:14
@tterava can confirm, LeelaZero is horrible unoptimized at very high playouts as I found out when testing myself a while back. so I'm not suprised of the bugs. and timeout etc... but when following along on also 4x TitanV, it seems the version of Leela they use plays wweaker moves than what is suggested by Lizzie.

**Comment by roy7** [comment] 2018-04-14 14:28
I would assume they are using the latest next branch, but I don't know for sure.

**Comment by bood** [comment] 2018-04-14 14:31
> I would assume they are using the latest next branch, but I don't know for sure.
 
Unfortunately not, v0.13 was used. So it appears v0.13 with pondering has serious problem. We'll try to avoid this in future games.

**Comment by hydrogenpi** [comment] 2018-04-14 14:33
@bood so tomorrow they will be using net 123?

**Comment by jillybob** [comment] 2018-04-14 14:38
@hydrogenpi please do a live stream with the 4 titans. I do not believe the owners of the LZ program had it working optimally. There is data on Cbaduk showing that 11% of moves were not reproducible https://www.reddit.com/r/cbaduk/comments/8c7qdx/in_game_1_of_lz_vs_golaxy_11_of_leela_zero_moves

**Comment by roy7** [comment] 2018-04-14 14:42
I really think the next client is the way to go. I use that for all of my bots. New features are well tested before being added, and bug fixes happen quickly. So I feel like the next client is always the safest choice.

**Comment by bood** [comment] 2018-04-14 14:43
Game log uploaded, looks like move 148 already mis-clicked though:


[20180414_LZ_Golaxy_1.txt.gz](https://github.com/gcp/leela-zero/files/1910473/20180414_LZ_Golaxy_1.txt.gz)

[20180414_LZ_Golaxy_1.sgf.gz](https://github.com/gcp/leela-zero/files/1910472/20180414_LZ_Golaxy_1.sgf.gz)

Winrate curve:
![20180414_lz_golaxy_1](https://user-images.githubusercontent.com/1168942/38769381-b677d070-4034-11e8-89e1-af09cd493f16.png)

**Comment by bood** [comment] 2018-04-14 14:44
> I really think the next client is the way to go. I use that for all of my bots. New features are well tested before being added, and bug fixes happen quickly. So I feel like the next client is always the safest choice.

True. But the operator is on a windows machine, no one's building a next branch version for him unfortunately.

**Comment by jillybob** [comment] 2018-04-14 14:50
I can compile next branch for you in about 12 his if no one else has.

**Comment by Splee99** [comment] 2018-04-14 15:05
Where can I download the sgf file of the game record?

**Comment by hydrogenpi** [comment] 2018-04-14 15:08
![image](https://user-images.githubusercontent.com/35181396/38769632-f5cf73c4-3fba-11e8-8a1d-36b86d1f5723.png)

**Comment by roy7** [comment] 2018-04-14 16:07
Linux runs much faster for Leela but it is what it is. :)

For spf of the game you can find it linked to my profile on ogs but I can't provide a direct link cuz I'm not at home at the moment. Look up roy7.

**Comment by billyswong** [comment] 2018-04-14 16:17
So no-pondering plus time-management-on means Leela Zero is a lot weaker than it could be. If the operator got a next-branch binary tomorrow, does that mean they can run with pondering-on then?

> since LZ pondering does not work perfect now, operator has to switch to time_setting 0 30 1 after 40 mins is used up

Would there any chance interfering in the middle of game affect the program stability?

**Comment by hydrogenpi** [comment] 2018-04-14 16:33
Had they used Linux, and next branch, and pondering, and not interferred midgame, and not misclicked, I'm curious if Golaxy would still have won?!?!

**Comment by godmoves** [comment] 2018-04-14 16:51
Actually, Golaxy is way much stronger than what you've imagined. And the match version got more than 4000 elo on cgos.

**Comment by ashinpan** [comment] 2018-04-14 17:04
@hydrogenpi  With the conditions mentioned by you fulfilled, LZ might have still lost but might have put up a tough fight before going down, not because of a stupid bug.

**Comment by afalturki** [comment] 2018-04-14 17:12
@bood I can build a next branch version from VS17. Are there things that I need to change in the code before I compile? (max tree value for example).

**Comment by Mardak** [comment] 2018-04-14 17:14
For anyone questioning the network and correctness of moves when following along with a leelaz analysis, don't forget about the 8 possible rotations. For example, move 14 from the game's log https://github.com/gcp/leela-zero/issues/1204#issuecomment-381333893

```
 D16 ->   96421 (V: 54.36%) (N:  0.73%) PV: D16 D17 E16 B15 Q16 Q17 P16 S15 P17 Q14 M4 M5 L5 L3 N5 M6 O4 N6 N4 M2 K5 J4 L16 J17 K7 H3 E17 J15 C14 C15 D14
  M4 ->   44879 (V: 53.94%) (N: 46.11%) PV: M4 L3 M5 M2 O4 N4 P4 N3 N5 L5 M7 N7 M6 M8 K7 P2 Q2 R3 R2 R8 K2 L2 J3 J4 H4 H5 J5 J6 K4 K5 L8
 Q16 ->   30343 (V: 54.26%) (N:  1.58%) PV: Q16 Q17 P16 S15 P17 Q14 L17 H3 C8 R8 M4 M5 L5 K5 L6 M6 K4 L3 K3 L2 J5 K2 K6 M7 S7
  L3 ->    5018 (V: 51.67%) (N: 41.99%) PV: L3 K4 K3 J4 J3 H4 H3 G4 F3 R3 R4 Q3 P4 P2 F6 C8 O4 G7 Q16 R16
```

Where in particular, notice M4 46.11% and L3 41.99% priors. Here's the priors for each of the 8 rotations using `5d6d9c5b-121`:
```
expect: D16, move: 14, who: w, weight: 5d6d9c5b, visit: 11
rotation: 0, seed: 22
  M4 ->       6 (V: 55.57%) (N: 40.99%) PV: M4 M5 L5 L3 L2 K2
  L3 ->       4 (V: 53.16%) (N: 38.57%) PV: L3 K4 K3 J4
= M4
rotation: 1, seed: 6
  M4 ->       5 (V: 56.22%) (N: 36.09%) PV: M4 M5 L5 L3 L2
  L3 ->       5 (V: 53.98%) (N: 47.85%) PV: L3 K4 J3 M4
= M4
rotation: 2, seed: 2
  M4 ->       8 (V: 57.34%) (N: 64.80%) PV: M4 M5 L5 L3 L2 K2 M2 K5
  L3 ->       2 (V: 53.72%) (N: 23.27%) PV: L3 K4
= M4
rotation: 3, seed: 11
  M4 ->       6 (V: 55.42%) (N: 46.71%) PV: M4 M5 L5 L3 L2 K2
  L3 ->       4 (V: 53.84%) (N: 36.36%) PV: L3 K4 M4 M5
= M4
rotation: 4, seed: 3
  M4 ->       6 (V: 55.21%) (N: 47.79%) PV: M4 M5 L5 L3 L2 K2
  L3 ->       4 (V: 54.30%) (N: 37.29%) PV: L3 K4 M4 M5
= M4
rotation: 5, seed: 4
  M4 ->       5 (V: 56.11%) (N: 37.97%) PV: M4 M5 L5 L3 L2
  L3 ->       5 (V: 54.35%) (N: 40.33%) PV: L3 K4 J3 M4
= M4
rotation: 6, seed: 12
  M4 ->       6 (V: 55.39%) (N: 46.11%) PV: M4 M5 L5 L3 L2 K2
  L3 ->       4 (V: 53.39%) (N: 41.99%) PV: L3 K4 K3 J4
= M4
rotation: 7, seed: 1
  M4 ->       6 (V: 56.00%) (N: 44.28%) PV: M4 M5 L5 L3 L2 K2
  L3 ->       4 (V: 52.21%) (N: 38.63%) PV: L3 K4 J3 M4
= M4
```
So for this move in the live game, looks like rotation 6 was used.

**Comment by hydrogenpi** [comment] 2018-04-14 21:08
what is the link for tomorrow?
630am cst?

**Comment by hydrogenpi** [comment] 2018-04-14 21:11
fyi playouts never hit above 300k, so max tree size is not gonna be an issue

**Comment by hydrogenpi** [comment] 2018-04-14 22:24
@jillybob okay I will be live st5reaming it tomorrow morning 
https://www.twitch.tv/hydrogenpi

**Comment by jillybob** [comment] 2018-04-15 02:46
Here is a compiled Windows version of the Next branch. @bood  You can use this version tonight.

https://drive.google.com/file/d/1obv9hf9wufcWyeYTJfK-6K0YtiGJD3H6/view?usp=sharing

**Comment by afalturki** [comment] 2018-04-15 04:13
@Vargooo np. It's not downloadable because it's constantly changing with new commits.

**Comment by hydrogenpi** [comment] 2018-04-15 05:04
For thoses that provided the compiles, this crashes in Lizzie, apparently Lizzie also mods the source code in order to output the stats and other stuff. Maybe Lizzie can make a wrapper around Leela instead of including it as compiled so in the future this would not require Lizzie to also recompile.

**Comment by Vargooo** [comment] 2018-04-15 05:15
@alfaturki 
OK , but couldn't there be a place where the compiled next versions would all be stored chronologically, and so, one could always download the latest version ?
Anyway, thx for your work.

**Comment by a22063821** [comment] 2018-04-15 06:44
@jillybob 
Next branch will crash!
I use next branch on win7 64bit
Move will crash in a few steps
Hope you can fix it as soon as possible!

**Comment by tterava** [comment] 2018-04-15 07:16
Next branch is indeed unstable. It just stops after a few moves on my setup and gets totally stuck.

**Comment by tterava** [comment] 2018-04-15 07:47
Even with Sabaki, next branch will crash on many setups. There's discussion about it in #1161 and a pull request that supposedly fixes it in #1179.

**Comment by jillybob** [comment] 2018-04-15 07:50
I was not able to reproduce this crash. Here is my command -g -t 4 -r 10 -w f32316820bae3a52227d1c6b8e04ca13c250209c0d782ba3d29bc7d68b71ed2f -p 50000 --noponder

**Comment by Ka-zam** [comment] 2018-04-15 08:10
Lizzie always crashes with next branch, that's a bug in LZ not Lizzie, and it's fixed here:
https://github.com/gcp/leela-zero/pull/1206

If you want to use next branch with Lizzie you need this fix and you also need to paste in the few lines of code that modifies UCTSearch::ponder() method. I could push these changes to my repo I suppose on a new nextlizzie branch.

**Comment by a22063821** [comment] 2018-04-15 09:40
@Ka-zam thx

**Comment by jillybob** [comment] 2018-04-15 10:08
https://drive.google.com/file/d/1dOemw_3JQuuL4ZVnbY_e1U2h7WN8NLVi/view?usp=sharing

Leela Zero Next Windows x64 works with lizzie, compiled including @Ka-zam modifications

**Comment by diadorak** [comment] 2018-04-15 10:48
An unofficial 20x256 network will be used today. Maybe the LZ team suspects Golaxy has prepared special openings, e.g. double 3x3, to throw LZ off.

**Comment by roy7** [comment] 2018-04-15 10:51
The 3-3 opening didn't seem a problem, LZ just eventually responded with 4-4 and the corners developed normally. LZ seemed to be losing the game before the technical problems, but of course it's just one game. :) Still, in theory the 20x256 net is stronger than the current official net.

**Comment by diadorak** [comment] 2018-04-15 10:53
Yes, LZ totally did not expect move 75. The win rate dived there.

**Comment by godmoves** [comment] 2018-04-15 10:54
Golaxy has a lot of time to prepare the match as all weights of Leela Zero are published before the game. So a new net may be a good choice.

**Comment by diadorak** [comment] 2018-04-15 10:59
The underdog should try all sorts of strategies :)

**Comment by billyswong** [comment] 2018-04-15 11:07
@diadorak will they try the new unofficial binary today or next match? A pondering-enabled game will be much stronger for Leela Zero, since Golaxy like to play slow.

**Comment by hydrogenpi** [comment] 2018-04-15 11:26
unofficial 20 by 256?so basically something they created themselves or something already pubically available

**Comment by ryouiki** [comment] 2018-04-15 14:55
In my brief test, f32316 performed better than 20x256 V6 when they used **same amount of visits**.
With time constraints, V6 has almost no chance to win f32316.
Though I don't know how much new 20x256 improved from V6,
I guess f32316 or it's successor would be the best choice for any kind of competition.

**Comment by jillybob** [comment] 2018-04-15 22:01
To be more accurate you will need to play 20b network with 100k playouts and 15b network with 150k playouts and compare

**Closed** 2018-04-16 03:10 UTC

**Comment by alreadydone** [comment] 2018-04-17 05:01
It's [said](http://www.yikeweiqi.com/banner/43784/) that they used another self-trained 256x20 network in the 3rd game (different from [V8 used in the 2nd game](https://www.reddit.com/r/cbaduk/comments/8cmnur/lizzie_vs_galaxy_game_3_link_5d_english_commentary/dxhd6pm/) and the official # 121 used in the 1st game).

A link to get official news and analysis from Yikeweiqi on PC without the app: http://www.yikeweiqi.com/?s=%E6%98%9F%E9%98%B5 All in Chinese, but variations are shown on the board.
[3rd game](http://www.yikeweiqi.com/banner/43794/)
[2nd game](http://www.yikeweiqi.com/banner/43758/)  [2nd game](www.yikeweiqi.com/banner/43754/) including Golaxy winrate and "difference in stones" graph so it looks like Golaxy trained a network to predict the score ...
[1st game](http://www.yikeweiqi.com/news/topline/43738/)  [1st game](http://www.yikeweiqi.com/banner/43722/)

**Comment by billyswong** [comment] 2018-04-17 07:10
@alreadydone Are they still using no-ponder for bug prevention? For the network, I would rather they use the official # 124, so far there is zero evidence that any self-made 256x20 net is stronger than the official 15 blocks in time-parity, while using official net makes the match result more "official".

No matter what, Golaxy wins easily and the tournament so far proves nothing, as they have double the computational power.

**Comment by alreadydone** [comment] 2018-04-17 07:40
@billyswong According to the [commentary](http://portal.yikeweiqi.com/online/golive/detail?id=8378) at move 104, LZ still wasn't using pondering in the 3rd game. I think they use self-made networks to avoid the Golaxy team studying and aiming for the weaknesses of the publicly available networks, though the effectiveness is questionable. It might also be preferable to use a larger network to max out the GPU and use less threads if it is truly stronger. They certainly did some tests to determine the strength, but since the V9 used in the 3rd game was trained up to # 116 (that is all 128x10 games) I doubt it will be much stronger. Anyway, @bjiyxo's [analysis](https://github.com/gcp/leela-zero/issues/1113#issuecomment-381854085) showed that the decisions of the newest official and self-made nets don't differ much.

**Comment by alreadydone** [comment] 2018-04-18 04:17
Golaxy ( 星阵(B) ) is now playing on Tygem, beating pros with one-stone handicap and 0 komi, demonstrating that it's indeed capable of playing with variable komi.
