### ISSUE TITLE
Add option to run self play only

### ISSUE THREAD

**Issue by bood** [gcp/leela-zero#549] opened 2018-01-03 03:29 UTC
In case people don't want to run matches for some reason, e.g. poor network cause the download fails a lot

@roy7 I can create a PR for this but what do you think is the best impl? I'm thinking of either requesting from a different url or add some query parameters like `?selfplay=1` for self-play only tasks.

**Comment by billyswong** [comment] 2018-01-03 04:06
Duplicate of #497

**Comment by bood** [comment] 2018-01-03 04:17
Ah, didn't see that. But I guess I'm attacking with a new angle :-)

**Comment by roy7** [comment] 2018-01-03 15:04
It does make sense people in China or with bad network links maybe don't want to keep downloading network files.

**Comment by marcocalignano** [comment] 2018-01-03 15:35
If the download fails autogtp falls back to the last successful self played game parameters

**Comment by billyswong** [comment] 2018-01-03 18:11
I still wish there will be self-play option release for slow computers that take >30mins to play one game. But gcp has marked "won't fix". I hope @bood your attack angle works.

**Comment by MartinDevelopment** [comment] 2018-01-03 19:40
If you really want to only play selfplay games you can change prog_cmdline.append(" http://zero-test.sjeng.org/get-task/7"); in Management.cpp to prog_cmdline.append(" http://zero-test.sjeng.org/get-task/0"); With this you will only play selfplay games.

**Comment by bood** [comment] 2018-01-04 00:08
but I remember seeing several retries before it fails？ I will check the
code later

2018年1月3日 23:35，"marcocalignano" <notifications@github.com>写道：

**Comment by marcocalignano** [comment] 2018-01-04 00:33
Yes it will try 4 times, I believe, with different intervals and the gives up and falls back to self played games

**Comment by bood** [comment] 2018-01-04 01:58
read the code, it will try 3 times in total, 30,45,67.5 seconds each, 135s
in total. On a poor network, this means extra 2 to 3 mins for each game
which seems to be a big waste to me.

@roy7 is it okay for you to request on get task0 for self play only games？

2018年1月4日 上午8:33，"marcocalignano" <notifications@github.com>写道：

**Comment by roy7** [comment] 2018-01-04 02:08
The /0 trick is in there mostly for testing/debugging purposes. Currently @gcp didn't want to add a true selfplay only option to the client, but that was more for people who thought their PC was too slow. For people with network issues that want to avoid all of the network downloads that seems like a decent use case. If @gcp is on board with the feature, I'll add better real support on the server.

**Comment by marcocalignano** [comment] 2018-01-04 07:35
The network connection is needed to upload the selfplayed game. Without upload it is a waste no matter which options you use. That is why the 3 min retry code. If you have a problem downloading a network (which is small compared to a game) you will have problems even when the best network changes. You will play a lot of selfplayed games with old networks.

**Comment by bood** [comment] 2018-01-04 07:58
1. network downloads and game uploads are placed on different server I
guess, uploads seem to be totally fine in China @roy7 correct me if I were
wrong
2. best network update are much less frequent than match network update,
even a manual update is fine

**Comment by gcp** [comment] 2018-01-04 09:59
It's the same server for everything.

**Closed by gcp** 2018-01-04 09:59 UTC
Labels: wontfix
