### ISSUE TITLE
Heatmap not deterministic on Mac with Intel GPU

### ISSUE THREAD

**Issue by jkiliani** [gcp/leela-zero#375] opened 2017-12-13 16:55 UTC
After doing some tests @killerducky encouraged me to, I found out that leelaz heatmap command is not repeatable on my machine. 
[heatmap3.txt](https://github.com/gcp/leela-zero/files/1556300/heatmap3.txt)

I did some testing, repeatedly calling the same heatmap from the starting position, using the supervised network. Here's the summary: Out of 43 identical function calls, 33 were correct, 10 were scrambled. The scrambled calls actually were identical between each other, just incorrect.

I opened a new issue for this since this looks like a major bug, most likely with OpenCL on some architectures.

**Comment by isty2e** [comment] 2017-12-13 17:07
Wow, this looks like a serious one, the heatmap became a total mess. What was the options for leelaz?

**Comment by killerducky** [comment] 2017-12-13 17:09
See also #359

**Comment by jkiliani** [comment] 2017-12-13 17:11
Shouldn't heatmap depend not at all on options? Anyway I used options as suggested by @killerducky in the thread about short games on AMD GPUs. I can look up the specifics in a while, using my phone atm.

**Comment by isty2e** [comment] 2017-12-13 17:11
Yes, what I was wondering is what options make this happen and how to reproduce it.

**Comment by jkiliani** [comment] 2017-12-13 17:17
I think it's likely to not be reproducible on every system. Since heatmap shows the raw neural network evaluations, I can only speculate that some hardware/software configurations mess up the NN calculation itself under certain conditions. I hope others here come up with more concrete theories, or ways to test which clients are affected.

**Comment by odeint** [comment] 2017-12-13 17:22
All those heatmap calls are just in the same Leela console, right? Without restarting or changing options in between?

**Comment by jkiliani** [comment] 2017-12-13 17:23
Correct, same console, no restarts, identical function call.

**Comment by marcocalignano** [comment] 2017-12-13 17:28
We are compiling our leelaz with the option -ffast-math. I think this makes the games not reproducible.

> -ffast-math
> This option allows GCC to violate some ANSI or IEEE rules and/or specifications in the interest of optimizing code for speed. For example, it allows the compiler to assume arguments to the sqrt function are non-negative numbers and that no floating-point values are NaNs.
> This option should never be turned on by any `-O' option since it can result in incorrect output for programs which depend on an exact implementation of IEEE or ANSI rules/specifications for math functions.

**Comment by jkiliani** [comment] 2017-12-13 18:52
@marcocalignano I just tried omitting -ffast-math and -O3, either, in the makefile. Neither removed the occurrences of the corrupted heatmaps.

**Comment by evanroberts85** [comment] 2017-12-13 19:03
Could it have something to do hardware memory errors, that could cause bits
to flip? How robust is the network to these kinds of minor errors?

**Comment by jkiliani** [comment] 2017-12-13 19:05
@evanroberts85 Good question, but if it was a random memory error, shouldn't it be a randomly scrambled heat map, instead of a wrong heat map that is identically wrong each time?

**Comment by ihavnoid** [comment] 2017-12-13 19:30
Can you describe what combination of hardware you are using, and what git SHA you are using?  Doing so we can try to triage which specific hardware has this problem...

**Comment by ihavnoid** [comment] 2017-12-13 19:31
One more thing - can you try using the CPU-only implementation of OpenCL and see if that problem exists?

**Comment by evanroberts85** [comment] 2017-12-13 19:35
If it is memory that is storing the network weights, it would generally stay the same in the memory for each simulation, but a flipped bit on an exponent could turn one weight from a value between 0 and 1 to a value in the millions which would destroy the whole network output?

**Comment by jkiliani** [comment] 2017-12-13 19:38
@ihavnoid Just look in the initialisation header of the log file I posed. MacBook Pro 2015, with MacOS HighSierra. I'll try CPU only if you can describe to me where I'd have to change the Makefile.

**Comment by killerducky** [comment] 2017-12-13 19:51
This should do it, can't test it right now.

OpenCL.cpp
Old:
`            this_score +=  100 * (d.getInfo<CL_DEVICE_TYPE>() == CL_DEVICE_TYPE_GPU);
`
New:
`            this_score +=  9999 * (d.getInfo<CL_DEVICE_TYPE>() == CL_DEVICE_TYPE_CPU);
`

**Comment by jkiliani** [comment] 2017-12-13 20:00
@killerducky I tried changing OpenCL.cpp as you suggest, and it does select the CPU. Unfortunately, upon calling heatmap:

Error in convolve: clEnqueueNDRangeKernel: -54
libc++abi.dylib: terminating with uncaught exception of type cl::Error: clEnqueueNDRangeKernel

Looks like this doesn't work, at least with the implementation of the neural network evaluation.

**Comment by evanroberts85** [comment] 2017-12-13 20:01
If you rerun the function call again now, are the incorrect outputs identical to the incorrect outputs last time? 

Seems like many modern GPUs have error correction code build it, not sure if this is relevent or not for neural networks.

**Comment by jkiliani** [comment] 2017-12-13 20:06
@evanroberts85 Yes, every time I got the incorrect outputs, they were identical to the last time. Seems the possible outputs are kind of binary deterministic: Either correct, or incorrect in always the same way.

**Comment by evanroberts85** [comment] 2017-12-13 20:08
Try restarting your computer to completely clear the memory?

**Comment by jkiliani** [comment] 2017-12-13 20:15
@evanroberts85 Tried rebooting. No change, incorrect output still occurring. Still same wrong heatmap.

**Comment by ihavnoid** [comment] 2017-12-13 20:41
I cant hardly believe this is a memory error simply that it seems to be too determinstic and too frequent.  If it is that frequent, your system should crash almost immediately.  I would guess that this is a mac specific bug... there seem to be some.

Unfortunately all I have is a Linux machine with a nvidia GPU, and I have zero mac development experience so I don't think I can help.  Anybody else?

**Comment by evanroberts85** [comment] 2017-12-13 20:46
It could be one of the variables in the code is not initialised? This might not be a problem with some compilers but cause exactly the type of behavior you are seeing with others.

see for details:
https://stackoverflow.com/questions/45532534/same-program-gives-different-outputs-everytime-i-run

**Comment by OmnipotentEntity** [comment] 2017-12-13 20:48
A random observation that no one has mentioned yet that might be significant somehow:

After the heatmap is becomes scrambled exactly every fourth invocation is also scrambled.

**Comment by jkiliani** [comment] 2017-12-13 21:28
Mac specific bug appears to be increasingly likely... I have a second Laptop with and Intel HD 5500, and Windows 8.1. Network eval is dreadfully slow obviously, but appears deterministic and correct. So I have to suspect "Accelerate" or something else Mac related is the culprit here.

**Comment by SebastienFaurite** [comment] 2017-12-13 21:34
You can perhaps try to boot on a ubuntu USB key. And see if you can reproduce. That way you will be sure to be on exactly the same hardware.

**Comment by roy7** [comment] 2017-12-13 21:38
I think I call @gcp commenting that MacOS has a notoriously buggy OpenCL implementation? Not sure though.

**Comment by jkiliani** [comment] 2017-12-13 21:52
Well it certainly looks as if @gcp was right on that score. However, seeing it confirmed suggests it may be a good idea to build a safeguard into leelaz to detect if the client cannot reliably compute the heatmap, and not to connect such a client to autogtp. It's obvious now I shouldn't use leelaz on the Mac anymore, but until now I only had the rather vague information "There may be difficulties with OpenCL"

**Comment by gcp** [comment] 2017-12-13 23:38
Does simply rerunning heatmap in the same, already started up, leelaz, show the different results? Or only on separate startups?

The former we can detect in a self-check, the latter not so much.

I will probably write the CPU implementation soon, and I guess I might be able to do it in away that it can be used to check the OpenCL implementation.

**Comment by NTT123** [comment] 2017-12-14 02:49
@jkiliani, if possible, you can take a look at my testing branch at https://github.com/NTT123/leela-zero/tree/testing

This is part of my effort to support Cuda and CuDNN with theano. Fortunately, theano also supports CPU with

e.g. `export THEANO_FLAGS='cast_policy=numpy+floatX,device=cpu,dnn.conv.algo_fwd=time_once,floatX=float32'`

This branch will compare the results from OpenCL with results from theano, if there is any discrepancy greater than 1e-4 in absolute value, it will print out "ERROR". If you run it awhile, say, 10 mins, without any error, you could have confidence that your OpenCL result is OK.

**Comment by marcocalignano** [comment] 2017-12-14 12:09
Following what @evanroberts85 said I read a bit the code.
When you calculate the possible moves and do all the OPEN_CL convolution and batch_norm etc.,  does not matter if the vectors are not initialized? 
https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/Network.cpp#L407-L415

**Comment by evanroberts85** [comment] 2017-12-14 12:43
You could try compiling with the the -Wuninitialized (gcc) paramater, which would warn you about any uninitialised values. Probably barking up the wrong tree though, the opencl libraries seem a much more likely to be the problem.

**Comment by NTT123** [comment] 2017-12-14 12:46
@marcocalignano, these vectors store outputs of neural network's layers, therefore, initialized values do not matter.

I'm also curious about the default value of these vectors. A quick google search suggests that the default value is zero. I ran `g++` with  `-Wuninitialized`, there is no warning and the outputs are zeros.

**Comment by isty2e** [comment] 2017-12-14 13:07
I tested this with my mac with intel GPU. It was reproducible, and did also happen for LZ 0.6, though the heatmap values when the error occurred were very different. After three identical outputs, different erroneous heatmap appeared with a periodicity of 3.

Fortunately, it has another GPU inside so my self-play contribution was unaffected.

**Comment by evanroberts85** [comment] 2017-12-14 13:13
So that narrows it down to the Intel GPU drivers not Mac OS X.

**Comment by isty2e** [comment] 2017-12-14 13:17
That would require a reboot, which I don't like to do now for some reasons... Anyway [#359](https://github.com/gcp/leela-zero/issues/359) complicates things, since it's not only intel GPU thing. Maybe we're missing something important in the OpenCL implementation of LZ...

**Comment by marcocalignano** [comment] 2017-12-14 13:21
@isty2e can you try to delete `-cl-mad-enable -cl-fast-relaxed-math` in this line and try again?
https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/OpenCL.cpp#L794

**Comment by isty2e** [comment] 2017-12-14 13:24
@marcocalignano Still the same bug occurs.

**Comment by gcp** [comment] 2017-12-14 15:02
My Intel iGPU on Windows seemed to work correctly and even gave reproducible results. Pretty sure you're going to find it's an issue with certain chip+driver combos being broken.

**Comment by isty2e** [comment] 2017-12-15 04:30
Maybe we can temporarily provide an automatic test functionality for this in another branch, and let it send diagnostics (OS, compiler, devices, -g 2, etc.) and debug outputs if needed to the server? It might help us figuring out exactly on which conditions this happens.

**Comment by gcp** [comment] 2017-12-15 12:40
I plan to automatically verify the result every 1/5000 evaluations or so and abort the program if we detect a discrepancy.

**Comment by isty2e** [comment] 2017-12-15 13:29
Clearly gcp should have done many tests already, but this is indeed an OpenCL issue. In Network::get_scored_moves_interval(), after opencl_net.forward(input_data, output_data), output_data is already messed up while input_data remains identical. I have no idea why this happens or why this has a periodicity.

**Comment by isty2e** [comment] 2017-12-15 13:46
I wonder if [clDNN](https://github.com/intel/clDNN) can help resolve this issue, though it seems too much of effort to do this for intel GPUs only, since this library is specific to intel GPUs...

**Comment by gcp** [comment] 2017-12-20 17:31
clDNN isn't going to unfuck the OpenCL driver.

**Comment by isty2e** [comment] 2017-12-20 17:37
I was not saying that it is guaranteed to solve the problem. What I thought was that it was made by intel so if they're aware of similar issues there might be some workarounds to prevent this from happening. But anyways due to the limited computational power of intel GPUs, I don't think it's worth testing considering the effort and time for another implementation.

**Comment by gcp** [comment] 2018-01-12 15:35
Going to close this: we now have working self-checks. The winograd branch also checks whether the GPU configurations it tries are correct, so it might be able to find a working config where the current code cannot.

**Closed by gcp** 2018-01-12 15:35 UTC

**Comment by jkiliani** [comment] 2018-01-12 15:50
@gcp: I just updated to the newest commits on /winograd when I read this, and tried again on Mac with Intel Iris 6100. No luck: The Winograd tuner finds a configuration that later fails the self-check. Will have to go back to CPU compilation.
