### ISSUE TITLE
Is the server down? 

### ISSUE THREAD

**Issue by pcengine** [gcp/leela-zero#229] opened 2017-12-02 12:40 UTC
I can not connect to the website: http://zero.sjeng.org.  
and autogtp seems not working because of that.
Anyone knows whats going on?

**Comment by isty2e** [comment] 2017-12-02 12:43
Seems like it is... I wonder what happened.

**Comment by Dorus** [comment] 2017-12-02 12:47
It is not down, i can randomly connect to it at http://zero.sjeng.org/ (gives an error page most of the time but sometimes it gives the normal page). Autogtp sometime does start too. However, the server is very erratic and out of 3 games i tried to upload, it refused two now. That where my 2 autogtp instances, and both shut down when the upload was refused.

I started one new autogtp intance, but i'm afraid it will fail to upload again and all my cpu/gpu cycles are wasted. Hope it's solved soon :(

**Comment by Alderi-Tokori** [comment] 2017-12-02 13:29
I hope it's not a malicious DDOS :/

**Comment by roy7** [comment] 2017-12-02 13:49
I swear I didn't break it this time. I'm able to connect to log in but it's super slow. I wonder if we ran into a RAM or CPU issue again. If it'll let me get in and look around I'll see what I can do.

**Comment by roy7** [comment] 2017-12-02 14:04
I can eventually get back the login/password prompt, but I never get the shell to come up. @gcp might need to just reboot the server, I'm not sure what happened or what's wrong. If it isn't a DDOS then it's starved for some sort of resource.

**Comment by bood** [comment] 2017-12-02 14:07
Maybe you should put some metric monitor there from now on. e.g. https://www.datadoghq.com/

**Comment by NTT123** [comment] 2017-12-02 14:13
I'm worry that I'm the cause of this accident.

It happened right after I start 100 autogtp instances **in parallel** by a bash shell `for` loop.

**Comment by roy7** [comment] 2017-12-02 14:24
I'm just not sure how that would crash things. The best-network-hash command is fast and light weight. I assume you already had the weights file or did you try to download 100 copies of it all at once? I wonder if autogtp has any locks to prevent multiple download of same network. Even so that is just bandwidth not crippling cpu or ram usage.

**Comment by marcocalignano** [comment] 2017-12-02 14:29
No autogtp do not have any (cross process) lock to prevent multiple download, that it is why there is the multi game version where there is only one thread that perform the connection tasks and multiple thread that make the games.

**Comment by roy7** [comment] 2017-12-02 15:09
$ uptime
15:10:02 up 39 days,  7:33,  6 users,  load average: 27.62, 25.93, 24.57

At least I can get to a command prompt now.

**Comment by gcp** [comment] 2017-12-02 15:10
Something happened that caused the node.js instance to eat up all remaining RAM, causing everything to get swapped to disk etc.

**Comment by roy7** [comment] 2017-12-02 15:11
Server just restarted so I brought the server process back up.

**Comment by roy7** [comment] 2017-12-02 15:15
If @NTT123's 100 connections were all trying to download the weights file simultaneously, I guess that could have done it then? Since it'd load the 7.6 megabytes of the best network into ram 100 times, and run 100 gzip's simultaneously.

Yes that's it.

$ grep -c "IPADDRHIDDEN downloaded" log
105

Since he ran 100 processes without the weights file, it tried to download it 100 times at the same time.

Should we 1- gzip best-network and just send it out ram instead of compressing it on demand, and 2- have autogtp do a lock of some sort when downloading the weights file so it doesn't do multiple simultaneous downloads?

**Comment by gcp** [comment] 2017-12-02 15:16
You can see that normally the node.js part is only like 50M-100M so something does seem to have gone wrong there.

**Comment by roy7** [comment] 2017-12-02 15:17
100 gzips of a 7meg file would be 700M RAM to read the files into memory, plus 100 gzip buffers while streaming the results out. That could explain it?

**Comment by gcp** [comment] 2017-12-02 15:18
>Should we 1- gzip best-network and just send it out ram instead of compressing it on demand

Should definitely do this. Saves a bunch of CPU too.

**Comment by gcp** [comment] 2017-12-02 15:18
Also if there's some way to limit the max amount of concurrent node.js requests....

**Comment by roy7** [comment] 2017-12-02 15:39
I guess we could gzip best-network in networks/ and have autogtp download http://zero.sjeng.org/networks/best-network.gz directly instead of even running it through a node endpoint.

**Comment by grolich** [comment] 2017-12-02 21:33
As a possibly related note, I've noticed that even hours after the crash there were no updates to new networks on http://zero.sjeng.org/ , either for better or worse nets, for a lot longer than anytime it took to update these before. I assume (perhaps incorrectly) that it is related to the crash.

Does the training need to restart the entire process each time such a thing happen? is there a plan to add checkpoints to mitigate that in the future (when training would be a lot slower than it is today)?

Also, is that reason for no update? or are there other issues, such as only starting to train at given times, restarting the count on played games for training etc.

Would be a shame if small accidents would cause unnecessarily long delays.

**Comment by roy7** [comment] 2017-12-02 21:40
Training is done on a separate system, so the web site crashing won't impact that. I can't speak to the status of training/etc though as that's all managed by @gcp.

**Comment by roy7** [comment] 2017-12-03 04:11
Ok, I don't want to roll it all live until I'm awake and around the computer, so it'll be tomorrow, but my test copy of the server software now includes two optimizations. 

1- /best-network-hash is cached and only calculated at startup or when networks/best-network.gz changes. It is calculated from network/best-network.gz

2- /best-network now pipes best-network.gz directly to the client instead of compressing it on demand, and it doesn't read the whole file into memory before sending to client. (I don't know how the black magic between the pipes works and if it'll still read the whole file anyway, or just read more as the client consumes data from the download pipe).

3- network/best-network is no longer used in my test copy. Once live, we only need a best-network.gz.

**Comment by grolich** [comment] 2017-12-03 04:33
Definitely a good thing to know.

Still wondering if it's responsible for the lack of nn status updates (whether better or worse) and how, but for now, it's definitely a very good thing to know. The less bad things that happen when a server goes down, the better :)

**Comment by roy7** [comment] 2017-12-03 14:22
Server is live with the optimizations I listed above, motivated by the crash from client overload. Shouldn't fail again from that specific type of situation. We can probably close this issue. :) I'll be watching closely all morning to be sure some subtle bug doesn't cause problems, but so far downloading/uploading is all working smoothly and clients are generating work fine.

**Closed** 2017-12-03 14:38 UTC
