### ISSUE TITLE
The server is crashed now.

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#2015] opened 2018-11-14 14:26 UTC
Network connection to server failed.
NetworkException: JSON parse error: illegal value

**Comment by bjiyxo** [comment] 2018-11-14 14:30
@roy7 @gcp may check the server.

**Comment by featurecat** [comment] 2018-11-14 16:03
wrong repo

**Comment by ggroggs** [comment] 2018-11-14 16:24
There's an SSL certificate problem which I suspect is the root cause: both started at the same time.

https://zero.sjeng.org/home is showing Error 526, Invalid SSL certificate, and I'm seeing the same error on an existing running autogtp when trying to upload a selfplay game.

**Comment by WeirdConstructor** [comment] 2018-11-14 18:44
You can actually download and reach the site via HTTP (without S). http://zero.sjeng.org/

**Comment by wonderingabout** [comment] 2018-11-14 19:15
nothing major,
we should get news soon or later, wait and see

**Comment by roy7** [comment] 2018-11-14 19:42
The SSL certificate I'm afraid has to rely on @gcp, I'm clueless on that.

**Comment by ggroggs** [comment] 2018-11-14 20:47
> You can actually download and reach the site via HTTP (without S). http://zero.sjeng.org/

Right, the site works fine without https; it's mostly autogtp that is affected for me right now, as that uses "curl https://zero.sjeng.org/get-task/" to get work orders, and that's returning the certificate error.

https:// on the main site is simply an easy way to observe the problem without running autogtp.

**Comment by l1t1** [comment] 2018-11-14 22:03
31 match games, only 4 clients played

**Comment by roy7** [comment] 2018-11-14 22:07
SSL should be fixed now.

**Comment by ggroggs** [comment] 2018-11-15 09:48
> SSL should be fixed now.

Looks good, thanks!

**Comment by gcp** [comment] 2018-11-15 10:54
Issue was forgetting to restart nginx after cert updates (which happened a while ago).

**Closed by gcp** 2018-11-15 10:54 UTC
