### ISSUE TITLE
Implement variable and/or abstract board sizes/configurations

### ISSUE THREAD

**Issue by wctgit** [gcp/leela-zero#753] opened 2018-01-26 14:02 UTC
_(This is perhaps a long-term 'wish' request, but on the other hand it might also be of practical use, or at least theoretical interest.)_

The current implementation seems to be hard-coded/fixed to a 19x19 board, but I wonder if there are more general principles of Go that might be learned by the NN if it was able to play on different sizes of boards: not only the traditional sizes of 13x13 and 9x9, but arbitrary (up to a limit) rectangular sizes, say from 1x1 or even 0x0 (just to prove the trivial boundary cases), up to 25x25 or even larger. Another interesting idea would be to allow for even board dimensions; why not 16x16 or 8x22?

While thinking about this, I thought, "What if you just had a network that could handle arbitrary shapes up to some large but not too large maximum width parameter, such as 25 or 30 or something along those lines? And who's to say that the board must be rectangular? Why not arbitrary shapes within that upper limit?"

So, the idea is fairly simple, actually: within a large square board, let's say 31x31 for argument's sake, a typical 19x19 board would be implemented by surrounding a central 19x19 square of 'open' board positions with a border of 'closed' board positions 6 spaces wide on each side. The main idea is that all possible board configurations would be 'centered' at a common centre (at (16,16) for the 31x31 example).

But within that space, and around that 'centre', you could literally have any configuration of 'open' and 'closed' board positions, including having 'closed' board positions _within_ the 'open' board positions.

This may even have some beneficial effects on the training of the convolutional NNs, since they would not only be sensitive to the 'edge' of a typical board, but they would also be sensitive to any 'closed' positions in any configuration. 

Simple examples to illustrate the possibilities: You could have a 'circular' board in a roughly circular shape (like a pixellated circle drawn on a bitmap); a doughnut shaped board with a small central 'closed' inner 'edge'; a lobed board, with two wide lobes connected by a narrow passage.

My naive imagination of how convolution works imagines a 'smallest square' convolution grid size, perhaps 6x6 or 3x3 or whatever, which scans the entire 31x31 board space, and for entirely-closed sections it obviously proposes no valid moves, but for mixed sections (with both closed and open positions) it proposes moves only within the open positions.

For training/self-play games, you could give the NN traditional board configurations, but also include randomized boards, with variously randomly generated boards of 'open' and 'closed' positions. You could give it lots of closed positions to see what kind of game play it can make out of it, or wide-open positions with scatterings of closed-position islands around.

For clarity, a 'closed' position would act exactly like an 'edge of the board' position, meaning that it cannot be played upon, and it provides no free liberties for adjacent pieces, but at the same time it does not count as an enemy stone in terms of capturing. The same Go rules would apply: any group which has its liberties reduced to zero would die, and you cannot play a suicidal move which would reduce your own group's liberties to zero.

The reason I think this might be of practical interest is that by training the NN with a **general** understanding of closed board positions, it **might** make the overall AI smarter in regards to playing at the edge of the board on traditional board sizes. Also, the exact same NN would be able to play all traditional board sizes, including more modern 'extreme' sizes like 5x5, 25x25, and non-square boards, as well as any custom board configuration that can be fit within the larger (e.g. 31x31) board 'canvas' or 'bitmap'. Therefore, you could have the same Leela Zero AI playing against any player on any typical board, and it would be equally strong no matter the size or shape of the board. Heck, due to learning more-general principles of play, it might even be stronger on a 19x19 board than if we stick with a NN that only knows a fixed 19x19 board-size.

Personally, I think it would be very cool. However, I understand that not only would it require big changes to existing code, but it would also be inevitably slower: slower to play on a typical 19x19, but also much slower to train, not only due to the sheer increase in maximum scale, but also since you would have to generate randomized board configurations (even if you stick to the three traditional board sizes) in order to generate the generalized understanding to play them all.

Anyway, just an idea.

**Comment by jkiliani** [comment] 2018-01-26 16:56
The idea is intriguing, but I see a major problem with the proposal: With Leela Zero, we're following in the footsteps of Alphago Zero, who proved that this particular technique works. Training a single neural net to learn to play on multiple board sizes would be pioneering AI research as far as I know. If you try things like this you have to expect a lot more setbacks, which no developer will seriously consider until the original project goal (Alphago like play on 19x19) is reached.

**Comment by Marcin1960** [comment] 2018-01-26 19:25
I would love to have 9x9 option

**Comment by wctgit** [comment] 2018-01-26 20:26
Also different komis and rulesets (Chinese, Japanese, etc.); I forgot to mention in the OP.

**Comment by yufanyufan** [comment] 2018-01-26 21:03
Supporting smaller board allow researchers to quickly test ideals like "[Multi-Labelled Value Networks for Computer Go](https://arxiv.org/ftp/arxiv/papers/1705/1705.10701.pdf)", and can be backport to the 19x19 games.

**Comment by Mardak** [comment] 2018-05-07 19:26
This is dupe of #24 and fixed / made trivial with #928

**Closed** 2018-05-07 19:38 UTC
