### ISSUE TITLE
Question: Participation in Computer Go UEC Cup 2018 - Financial Support

### ISSUE THREAD

**Issue by ThePokerDude** [gcp/leela-zero#1101] opened 2018-03-25 12:01 UTC
Hi,

as LeelaZero is getting stronger and stronger and certainly would be one of the favourites,
it would be cool if it could participate.
Maybe @gcp or one of the other main contributors would like to participate and represent the project.

But a trip to Japan and a participation is expensive.

If a lot of the enthusiasts of this project would donate something like 20€ we could collect enough for flights and hotel.

**Comment by Cabu** [comment] 2018-03-25 12:25
That's a good point :)

**Comment by l1t1** [comment] 2018-03-25 13:36
if a japanese contributor has a supercomputer, he can go easily

**Comment by ThorAvaTahr** [comment] 2018-03-25 13:46
it would be interesting to have a LZ as a participant

**Comment by arondes** [comment] 2018-03-25 15:49
a Chinese website yikeweiqi is holding a tournament of leela zero vs pro players. they use 4 Titan V and should be strong enough. may be a delegate.

**Comment by carljohanr** [comment] 2018-03-25 17:42
When is the tournament and where can I watch games?

**Comment by Hersmunch** [comment] 2018-03-25 17:48
https://en.wikipedia.org/wiki/Computer_Go_UEC_Cup
> UEC Cup was terminated after its 10th edition in 2017 and was succeed by AI Ryusei, a new computer Go tournament sponsored by Japanese Igo & Shogi Channel.[3]

AI Ryusei was held in December last year.

**Comment by hydrogenpi** [comment] 2018-03-25 18:21
Does he have a patreon, indiegogo for gofundme pages

**Comment by ihavnoid** [comment] 2018-03-25 18:57
Hmm if it's a tournament from Japan, isn't it going to play 6.5 komi using Japanese rules?  I wonder what we need to do to retrain the net to adjust to the different rule.  Especially training against Japanese rules...

**Comment by Hersmunch** [comment] 2018-03-25 19:00
Last year that was the case https://www.igoshogi.net/ai_ryusei/01/en/rules.html
> 1. Handicap
> Even game. The first player starts already with 6.5 points.

> 4. Ending procedure and game result
> Based on the Japanese Rules of Go(1989), except the following ending procedure....

**Comment by hydrogenpi** [comment] 2018-03-25 19:17
The prize award converted into USD woudln't even cover the cost of the flight lol

**Comment by l1t1** [comment] 2018-03-26 00:55
https://www.theregister.co.uk/2018/03/21/nvidia_titan_v_reproducibility/
2 + 2 = 4, er, 4.1, no, 4.3... Nvidia's Titan V GPUs spit out 'wrong answers' in scientific simulations

**Comment by luigio** [comment] 2018-03-26 01:15
The game ending procedure is bizarre.

**Comment by billyswong** [comment] 2018-03-26 06:28
> Hmm if it's a tournament from Japan, isn't it going to play 6.5 komi using Japanese rules? I wonder what we need to do to retrain the net to adjust to the different rule. Especially training against Japanese rules...

Hand-made algorithms to filter out moves that play inside self territory "unnecessarily"?

**Comment by luigio** [comment] 2018-03-26 08:13
Also, when Leela plays as Black, set komi internally to 5.5. (As White, set komi to 6.5.)

**Comment by gcp** [comment] 2018-03-26 12:01
>Also, when Leela plays as Black, set komi internally to 5.5. (As White, set komi to 6.5.)

Leela Zero doesn't actually care what the komi is set as. It only knows 7.5 because that's what it's trained with. It will correct the scoring functions but do nothing to the program understanding.

**Comment by gcp** [comment] 2018-03-26 12:07
I don't think it's a good idea to let Leela Zero play in a tournament held with Japanese rules. Nothing good can come of that.

You can build a program that supports Japanese rules [1] off of Leela Zero but I think it's out of scope for this project. 

[1] First task: try to determine a consistent set of rules that is not self-contradictory, matches Japanese custom and can be implemented. Good luck!

**Closed** 2018-03-26 12:07 UTC
