### ISSUE TITLE
20x256 training progress note

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#1674] opened 2018-07-30 14:20 UTC
Since 20x256 doesn't fall into place and the original issue #1113 is too big, I open a new issue to discuss here.

These are the parameters I used:
Batch Size=256
Learning Rate=0.0001 (10e-4)
The training window contains ~630k games, 350 lz games and 280k elf games.

Also, it looks like the official 20x256 are pretty bad now (almost every 20x256 gets ~20% win rate), so I will continue to train the new 20x256 when @gcp releases new raw training data in #167.

**Comment by jkiliani** [comment] 2018-07-30 14:35
It is strange that the official first training run was so unsuccessful, since it should be trained on very similar data to V21 nets. Maybe @gcp could share the current settings for batch size and learning rate?

By the way, are the bootstrap nets using SWA?

**Comment by alphaladder** [comment] 2018-07-30 18:05
Just because 15b is over-trained. We enjoy the bonus of ELF previously,now it is time to afford its side effect.

**Comment by gcp** [comment] 2018-07-30 18:52
It's the same settings are before the last learning rate lowering, but adapted for the fact that the new net wouldn't fit into RAM with the original batch size, i.e. it's now bs = 128 @ 0.00035.

>Also, it looks like the official 20x256 are pretty bad now (almost every 20x256 gets ~20% win rate

These are simply the same training as always but based on the V20-2 net that was promoted. For some reason even minimal training immediately makes this terrible.

**Comment by gcp** [comment] 2018-07-30 19:04
>Just because 15b is over-trained.

I have no idea what that is supposed to mean.

**Comment by Eddh** [comment] 2018-07-30 19:17
so it seems like training more on non-ELF games make it play less like ELF and more like Leela, so worse. But at the same time ELF games are not numerous enough for supervised learning, and training more on the few lead to overfit ? Then the only surprise is why there was no sign of overfitting in the main training pipeline despite a lot of steps spent on the same games. Maybe the LR of the main pipeline is a bit too high to overfit ? This situation is very confusing.

**Comment by Eddh** [comment] 2018-07-30 19:25
It might be an option to generate more ELF games to be able to do supervised learning on it. For training on 1 M games we would need 500k ELF, 500k LZ ?

**Comment by jkiliani** [comment] 2018-07-30 19:30
Isn't 128 @ 0.00035 equivalent to half the steps at 256 @ 0.0007? In that case, the current learning rate would be 7 times that used for the bootstrap, and it wouldn't be all that surprising that we're not currently seeing passed nets. But the self-play games from the bootstrap games should eventually be worth considerably more than the 15 block games, so maybe we can wait a while if the average performance of the networks improves with more 20 block games in the dataset?

If that doesn't work, than gradually lowering learning rates might be necessary. But if at all possible, using the higher learning rates first would likely be better in the long term...

**Comment by gcp** [comment] 2018-07-30 19:31
>maybe we can wait a while if the average performance of the networks improves with more 20 
>block games in the dataset?
>
>If that doesn't work, than gradually lowering learning rates might be necessary. But if at all possible, using 
>the higher learning rates first would likely be better in the long term...

This is my current thinking, yes.

**Comment by gcp** [comment] 2018-07-30 19:32
>It might be an option to generate more ELF games to be able to do supervised learning on it.

That would allow eventually training a super-ELF, sure, but again no guarantee (apparently!) that we can train on from that.

**Comment by Eddh** [comment] 2018-07-30 19:44
> maybe we can wait a while if the average performance of the networks improves with more 20
block games in the dataset?

The other problem is that the 20 block games are with 1600 visits, so obviously a lower quality than before. They will probably not help with the current problem.

**Comment by Mardak** [comment] 2018-07-30 19:46
> I'm just letting the regular training procedure run as always, which is the 500k last self-play games.

So it sounds like there's 2 main differences from bjiyxo: learning rate and training window.

The last 500k self-play games includes those from LZ155 through LZ159 with roughly half of that from LZ157.

V21 is also roughly half LZ157 but the other half is ELF instead of LZ data.

**Comment by jkiliani** [comment] 2018-07-30 19:49
> The other problem is that the 20 block games are with 1600 visits, so obviously a lower quality than before. They will probably not help with the current problem.

The current positive trend in match performance seems to rather contradict this. The last training run had no 256x20 games yet, only 192x15 at 3200. The current one has some 256x20 games at 1600 visits, and yet is performing better. Why worry about the visit count if current data doesn't actually point to a problem?

**Comment by gcp** [comment] 2018-07-30 19:50
>The other problem is that the 20 block games are with 1600 visits, so obviously a lower quality than before. They will probably not help with the current problem.

Hmm, that's a good point too. This means the training data is about ~50 Elo less than what was already in the window. This kind of change wouldn't have been a problem if the bootstraps were clearly stronger, but they were not.

That said, dropping to 17% happened with only a tiny fraction of the window being new games, so it's unlikely to be the cause.

**Comment by Mardak** [comment] 2018-07-30 19:55
The two V20 networks from bjiyxo also had much lower 20% win rates when training without ELF data:

V20 (0c77d215) training up to 050375ce (156)
0c77d215  VS  fc5e0a50 | 16 : 56 (22.22%) | 72 / 40
rating | 11612

V20-2 (dc011d01) training up to 050375ce (156) (including ELF's selfplay)
dc011d01  VS  d351f06e | 102 : 122 (45.54%) | 224 / 400
rating | 11775

**Comment by gcp** [comment] 2018-07-30 19:57
Another way to see that is that the current net is 11844 and producing data at a level of, say +550 Elo over that = 12394 Elo, whereas before we had 11806 + 650 Elo = 12456 Elo.

The question is now if, say, 500k games of some mixture of ~12400 to ~12450 Elo is good enough to train a network (which should have spare capacity) to >11844 Elo. That should be true, regardless of those 50 Elo difference.

**Comment by gcp** [comment] 2018-07-30 19:59
>The two V20 networks from bjiyxo also had much lower 20% win rates when training without ELF dat

Adding it back is surely worth a test.

I thought it was no longer needed because the previous nets didn't seem to mind much, but maybe this one is in a different position, in the, uh, optimization space.

**Comment by gcp** [comment] 2018-07-30 20:05
>Then the only surprise is why there was no sign of overfitting in the main training pipeline despite a lot of steps spent on the same games. Maybe the LR of the main pipeline is a bit too high to overfit ?

The smaller size of the network might have helped it to be forced to generalize better on the combined data. The larger network can differentiate between the two, and, seeing the ELF data disappear from training, forgets about it near immediately. Or something like that. Just wild theories with no data.

Maybe changing all variables at once wasn't a good idea. Yes, you can take off all your Captain Obvious In Hindsight hats off.

**Comment by Mardak** [comment] 2018-07-30 20:08
> The current positive trend in match performance

> current net is 11844 and producing data at a level of, say +550 Elo over that = 12394 Elo

I believe the positive trend is also that LZ155 data is shifting out of the window, where those games dropping out are of 11729 + 650 = 12379 Elo, which is getting replaced by 12394 Elo 256x20 1600 visit games.

**Comment by Eddh** [comment] 2018-07-30 20:11
> The current positive trend in match performance seems to rather contradict this. The last training run had no 256x20 games yet, only 192x15 at 3200. The current one has some 256x20 games at 1600 visits, and yet is performing better. Why worry about the visit count if current data doesn't actually point to a problem?

If I'm not mistaken these 2 runs were started from different @bjiyxo networks, the first dc01, the second 5a5e, so it's hard to know what to attribute this small rise to. The sample size is also small. We will see over the next few days what happens.

**Comment by TFiFiE** [comment] 2018-07-30 20:12
Since the transition has been messy anyway, maybe forcibly promote 511034f4 and get more training diversity as a bonus?

**Comment by herazul** [comment] 2018-07-30 20:30
i think the best bet is to train a 40b net without going to crazy on the training and learning rate, and if the 40b net can score something like a 60% wr or so, the transition will be much much better and smoother. An over-trained (as in, a lot of steps and LR reduction) may not be the solution.

**Comment by gcp** [comment] 2018-07-30 20:31
>Since the transition has been messy anyway, maybe forcibly promote 511034f4 and get more training diversity as a bonus?

That's OK by me. @roy7

**Comment by alphaladder** [comment] 2018-07-30 20:35
@gcp bjiyxo has applied 1080ti x2 to train his network,thus,maybe you could evaluate the possibility to update your 1070 for our new 20b. The possible effective learning rate of 1070 for 20b at bs128 may be 0.00005.

15b network is linearized by elf games and the raw 20b may be also linearized by new elf games.

**Comment by gcp** [comment] 2018-07-30 20:36
>i think the best bet is to train a 40b net without going to crazy on the training and learning rate, and if the 40b net can score something like a 60% wr or so

I have a 256x30 trained but the winrate wasn't above 50% against the 192x15 FWIW, so obviously the IF there is problematic.

**Comment by gcp** [comment] 2018-07-30 20:37
>bjiyxo has applied 1080ti x2 to train his network,thus,maybe you could evaluate the possibility to update your 1070 for our new 20b.

The problem has nothing to do with hardware, or training steps, and I'm not using 1070, etc. I also have no idea what "linearized" means.

**Comment by gcp** [comment] 2018-07-30 20:47
>I believe the positive trend is also that LZ155 data is shifting out of the window, where those games dropping out are of 11729 + 650 = 12379 Elo, which is getting replaced by 12394 Elo 256x20 1600 visit games.

So, another change caused by removing ELF is that there are now 250k more "old" games in the window (500k LZ instead of 250k+250k).

**Comment by l1t1** [comment] 2018-07-31 00:01
as sometime weights' match shows rock-paper-scissors result.
suggest to test match vs elf  for each weight to be  promoted ,

**Comment by fell111** [comment] 2018-07-31 02:13
According to #1673 ELF has a new version of network. We can have some of the self play games coming from it. I think that will do help with the progress.

**Comment by davikrehalt** [comment] 2018-07-31 10:31
If it’s indeed stuck in a narrow minimia wouldn’t it make sense to disable gating for a little bit and allow it to drop a little in the hopes of it coming back up? Alternatively maybe have someone else do that on the side (train without gating with larger learning rate) and replace the network when it’s equal strength?

**Comment by MartinDevelopment** [comment] 2018-07-31 11:34
New ELF weight for anyone interested, still need someone to port it to leela-zero.

https://github.com/pytorch/ELF/releases/tag/pretrained-go-19x19-v1

**Comment by afalturki** [comment] 2018-07-31 12:43
> If it’s indeed stuck in a narrow minimia wouldn’t it make sense to disable gating for a little bit

Dropping gating is a really dangerous option that should be the last resort in my opinion. As experience with lc0 showed, it might not come back up.

**Comment by TFiFiE** [comment] 2018-07-31 19:51
> It should also narrow the visit gap even more.

What do you mean?

**Comment by bubblesld** [comment] 2018-08-01 04:04
I help bjiyxo train 40b-LZ. I would like to share my experience in training. 

1.	I got good results with learning rate 0.0001, and I usually see improvement after 200k. The higher learning rate usually produces poor results. I tried 0.001/0.0005 to speed up the process, but the results are poor. 

2.	bjiyxo tried to train with no elf games. I tried to train with half of games being elf. Neither produced good results. We found that it can usually produce good results with elf-games being 30-40%. I found that the weight of 40b has a much lower mse to 15b games than elf games. That means, the weights of lz and elf are very different now. My conjecture is that elf can provide a direction that is much better. However, since they are far away, the weights will not improve in that direction locally. Then the better way is to find a good path locally with a little help from elf (The dimension is huge. It is difficult to find a good path, and an optimal path locally may lead to local minimum. We can look it in the way as elf reduces the selection region and then LZ find the optimal path in this region).

**Comment by 22nsuk** [comment] 2018-08-01 04:33
I am also making my own network and I have come to a conclusion similar to the above (I have not reached a good result yet).
Although the elf game has better results than none. For now, however, the optimal value is likely to be less than 50% of the total window size (I am currently testing 20 to 25% elf).
Thank you for revealing your know-how. @bubblesld

**Comment by bubblesld** [comment] 2018-08-01 05:25
@22nsuk 
Currently, we only train to v155. The strength is at the same level of elf1. I tested it against elf2 with 3200v for 132 games. The result is 59:73, about 40% winning rate.

**Comment by herazul** [comment] 2018-08-01 08:16
Thanks for the work @bubblesld and @bjiyxo ! your 40b network seems awesome.

@gcp according to this it would maybe be good for the training to reduce a little the % of elf games in the training ?
And if 40b net achieve something like 65% wr or more against current best, woudn't it be good to jump to 40b net directly ?

**Comment by Mardak** [comment] 2018-08-01 08:45
> We found that it can usually produce good results with elf-games being 30-40%.

I suppose if we want to maintain a fixed 500k window, then randomly sampling 150k to 200k ELF games (instead of the proposed 250k https://github.com/gcp/leela-zero/issues/1673#issuecomment-409247863) would be in that ratio. Although with all this magic, who knows what it should be with ELFv1 self-play coming in…

**Comment by 22nsuk** [comment] 2018-08-01 09:02
@bubblesld Currently, elf2 self-play is running at 25% of the total. If you wait a little longer, new data will appear.

**Comment by l1t1** [comment] 2018-08-01 09:04
@gcp can you queue a match vs elf once 40b weight is released to public

**Comment by TFiFiE** [comment] 2018-08-01 11:32
> Right now there's mixed data between 3200 visits and 1600 visits. 1600 visits on ELFv1 should be quite similar to 3200 on ELFv0.

But how does this relate to 511034f4 being promoted over 5a5e7393?

**Comment by roy7** [comment] 2018-08-01 13:34
> bjiyxo tried to train with no elf games. I tried to train with half of games being elf. Neither produced good results. We found that it can usually produce good results with elf-games being 30-40%. I found that the weight of 40b has a much lower mse to 15b games than elf games. That means, the weights of lz and elf are very different now. My conjecture is that elf can provide a direction that is much better. However, since they are far away, the weights will not improve in that direction locally.

This has been my concern although I have no evidence or facts to back it up, that if a given position has two very different training targets from LZ vs ELF, it'll end up with a wishy washy result that doesn't commit to either direction. Using less than 50% ELF games so that the weight of training is pushed towards LZ's prior beliefs is any interesting solution. Then the NN can learn from ELF, or filter it out as noise, as needed to keep progressing. At 50/50, which is signal and which is noise?

**Comment by bjiyxo** [comment] 2018-08-01 16:07
v22-64k.zip (containing half 155+156+157+elfv0)
https://drive.google.com/file/d/1p-pDDRdVTqIAci7luXpV1Y3xtQDlyOwv/view?usp=sharing
@gcp Can you match v22-64k.zip in queue?

**Comment by l1t1** [comment] 2018-08-04 01:02
20b 7a8a0c1a is stronger than 511034f4 79 : 75 (51.30%)now

**Comment by roy7** [comment] 2018-08-04 03:56
@bjiyxo If you pop on discord sometime I can give you instructions on how to queue these yourself. :)

**Comment by bjiyxo** [comment] 2018-08-04 18:01
I upload a new version 20b without elf-v0 data, and it contains 155-157.
b084:5110=53:37 on my computer, so it might be worth to try.

**Comment by alphaladder** [comment] 2018-08-04 20:34
v22 is now passed。

**Comment by l1t1** [comment] 2018-08-04 22:06
v22 72k, it seems the step interval decrease to 16k
and the match took longer time

**Comment by l1t1** [comment] 2018-08-05 02:38
ac666d3d is the first lz trained 20b weight that is stronger than bjiyxo's weight

**Comment by kfc51151271** [comment] 2018-08-05 02:55
ac666d3d looks good, with a winrate of more than 50, and it might get a PASS if it was born earlier. Anyway, it shows a good trend.

**Comment by alphaladder** [comment] 2018-08-05 04:04
Amazing test! Could you mind let us know this promotion is the contribution of either elf games or lower learning rate?@gcp. Thanks.

**Comment by l1t1** [comment] 2018-08-05 09:16
d63fb75a looks better than ac666d3d by now, gcp must have found the right way to train 20b weights

**Comment by 2ji3150** [comment] 2018-08-05 14:57
Well, looks like the 67742f28 is passed by not promoted.
https://i.imgur.com/ecl2g6j.jpg

**Comment by jokkebk** [comment] 2018-08-05 21:08
67742f28 seems to have beaten the bjiyxo V22 net to become the first "normally trained" 256x20 net to pass the gating? Congratulations 677! (better that than a 666 beast :)

Hope this will start a prosperous era of standard training with 256x20 without need for external training. Then we can all focus on arguing when to switch to 40b. 😆 I liked the idea that client could choose to use the quite strong 40b network to generate self-play games, although with 57 % winrate (referenced in another thread) against 160, it might be just a few promotions and the latest 20b is already stronger.

Btw. why always self-play within same network? Wouldn't games between two different nets be potentially even more "educational" material for the training process?

**Comment by alphaladder** [comment] 2018-08-05 21:19
@jokkebk very interesting idea. Let us see GCP ‘s decision on the time of the transition from 20b to 40b. 

Maybe we should see if bjyxo has other 40b weights trained  when more 20b games are accumulated.The previous 40b in the queue is only based on the old 15b self play games.

**Comment by l1t1** [comment] 2018-08-06 06:32
someone in tieba says 162 is weaker than 157 weight by his tests.

**Comment by 2ji3150** [comment] 2018-08-06 07:06
> someone in tieba says 162 is weaker than 157 weight by his tests.

Common, only Few Tens of Matching is meaningless. Don't always repost things without any statistical significance. someone said something is really meaningless.

**Comment by 2ji3150** [comment] 2018-08-06 11:45
@l1t1 
Do you know what is the error? Do you know what is sprt? Do you know what statistics are?
I say again, don't always repost things without any statistical significance. 
Test for 200 or 400 games and attach the sgfs here or it it meaningless for us that who said something.
Do not waste our resource for meaningless matching. It doesn't make sense.
And I saw you are always doing this.

Looks like bunch of (Chinese?) people who didn’t have a computer science background from the QQ group recently create lots of new accounts without any github activities and tried to influence the plan by their own opnions without making sense. At least it is very annoying for me.

**Comment by l1t1** [comment] 2018-08-06 12:39
the elo is calculated by sprt, but each time elf take a new match, its elo changed, that proves sprt and elo is not as reliable as they seems to be

**Comment by MartinDevelopment** [comment] 2018-08-06 12:54
Why does it matter even if 157 is stronger than 162 at the same time settings? The 20 block network is still improving while the 15 block wasn't.

SPRT was never meant to be reliable to measure the strength difference over a long time. It was only meant to measure if a network is 35 Elo stronger than the previous one or not.

**Comment by roy7** [comment] 2018-08-06 12:56
The self play Elo is in no way expected to be a fixed number if compared to something outside of the selfplay. Its purpose is just to measure the relative distance between two LZ networks.

**Comment by 2ji3150** [comment] 2018-08-06 13:10
@l1t1  20b is now iterate very fast. It is still being stronger and stronger. Just the 163 is going to passed. We don't need to waste the resorce for the matching that doesn't help the 20b. And there should be new match with the elf v1 few days latter. Then you can know the resault of which the latest network is stronger of not.

**Comment by Friday9i** [comment] 2018-08-07 10:10
Not so surprisingly after training very well the 15b net (with Elf's help), it seems the potential of the 20b net is relatively limited: around 1000 selfplay Elo? Hence, the time to improve with new nets is quite long.
In these circumstances, with a powerful 40b net available and with much more potential, it may be a good idea to switch to the 40b soon...

**Comment by jkiliani** [comment] 2018-08-07 10:27
I don't see how the potential of 20b would be limited, any more than the potential of earlier architectures was... 40b is an option when 20b slows but there's definitely no hurry for now.

**Comment by john45678** [comment] 2018-08-07 11:29
I think that 20b has been made a 'standard' by DM and to match a best LZ 20b with (what we know about) AZ 20b and ELF would be one of the most interesting outcomes of this project (so far).

Of course I understand that a 40b training starting now would be quicker strength wise and may be needed if 20b fails to improve.

**Comment by tapsika** [comment] 2018-08-07 13:33
The potential of 20b is not clear at the moment. Results of recent nets show a decreased saturation (they got closer to 50% from both directions). This seems a natural consequence of running eval matches with half visits. Since we know saturation scales with visits, getting over 55% is significantly harder now than was for 15b.

In fact, evaluating matches with higher visits would offer a relatively safe compromise to the gating debate, since it amplifies the signal without affecting the noise (unlike changing the threshold or the number of games).

**Comment by ashinpan** [comment] 2018-08-07 15:11
@tapsika You mean that even if self-play games are run with 1600 visits, matches should be with, e.g., 3200 visits. I think this is a good idea.

**Comment by tapsika** [comment] 2018-08-07 16:17
I meant maybe even more visits. The same nets that would match to 55% result at 3200 visits would probably get 53-54% at 1600 visits but 56% at 6400 visits. This allows selecting stronger nets more reliably, without increasing random variance and passing by luck. (remember https://github.com/gcp/leela-zero/issues/1113#issuecomment-384711402)

**Comment by l1t1** [comment] 2018-08-09 12:08
https://lifein19x19.com/viewtopic.php?f=18&t=15718&start=80 also point out same time question of 157 vs 161

**Comment by bjiyxo** [comment] 2018-08-09 13:38
Sorry, I match 40b vs 20b by accident and if 40b wins it will promote. So if @gcp or @roy7 is not here, I will match 20b vs 5b to get a quick fix.

**Comment by bjiyxo** [comment] 2018-08-09 13:56
Fixed by Roy7

**Comment by odeint** [comment] 2018-08-09 17:00
The latest test results of @bjiyxo 40b-157-360k (e2be4815) against the latest version of Facebook ELF (v1, d13c4099) are surprising and really encouraging - especially since this was achieved with just 192x15 data and ELF v0 data, yet it is stronger against v1 than either of those  (and the 256x20 trained on the same data).

Before, I agreed with the approach of first running 256x20 for at least a few more cycles to see how that goes. Now I support the calls for an expedited upgrade to 256x40 despite the hit on game generation rate - the bigger architecture actually generalises considerably better on the same data, almost on par with ELF v1, while 256x20 had problems to even overcome the best 192x15. I'd still like to understand why, but the data is now clear that this is the case.

**Comment by TFiFiE** [comment] 2018-08-09 23:18
I'd like to hear what @gcp thinks of tapsika's idea of increasing the number of visits in matches only.

**Comment by gjm11** [comment] 2018-08-09 23:53
15 (or even 20) to 40 seems like a really big jump. Maybe there's a reason why numbers like 20 and 40 are particularly good (e.g., perhaps something nice happens when you get beyond 2x the size of the board or something) but (especially for a program that people with "ordinary" hardware use) it seems like it might be worth seeing what an intermediate-sized network can do before going all the way to 40.

**Comment by l1t1** [comment] 2018-08-11 05:07
jma127 
commented about 3 hours ago
Hi @herazul , thanks for your interest! Github issue tracker is a perfectly fine place to post general questions 😄

By my rough count,  approximately 2.4 million games between v0 and v1.

**Comment by PhilipFRipper** [comment] 2018-08-11 08:39
Since lowering learning rate made the 20x256 networks competitive, would lowering it more make them MORE competitive?

**Comment by jkiliani** [comment] 2018-08-11 08:47
Learning rates now are already the lowest they have even been on official Leela networks, lower than @gcp is really comfortable with as I understand him. The problem with very low learning rates is that they can get you stuck in local optima if used too early. Right now we have no choice about using them anyway since higher learning rates were unable to produce a network that promoted...

**Comment by anonymousAwesome** [comment] 2018-08-12 05:17
So what if we backtracked?  Raise the learning rate by a lot, then force-promote a network or two?

**Comment by jkiliani** [comment] 2018-08-12 07:00
One disadvantage of removing the steps up to 512k is that the match/training game ratio went up, a lot. Maybe we don't actually need to test the 32k and 96k nets?

**Comment by TFiFiE** [comment] 2018-08-12 15:13
**c910dee9** passed a bit early for such a modest winrate.

**Comment by wonderingabout** [comment] 2018-08-12 16:00
its not too late if you want to unpromote it.. (51% winrate)

**Comment by diadorak** [comment] 2018-08-12 19:55
Wow it took ELF 2.4 million games to improve v0 to v1.

That makes the new 40B's winrate against ELF v1 even more impressive!

**Comment by herazul** [comment] 2018-08-12 20:30
yep 2.4 million games is quite a lot indeed, we clearly don't have the fire power to bruteforce our way to elf v1 strengh level on 20b.
The godly 40b is a very good opportunity to get us there a lot quicker  =)

**Comment by alphaladder** [comment] 2018-08-13 05:10
Yes. Dr. Tian’s contribution is amazing in 20b training, which will accelerate our way to 40b.

**Comment by jillybob** [comment] 2018-08-13 07:11
If we can get these 2.4 million ELF games, I will be very happy!

**Comment by roy7** [comment] 2018-08-15 13:05
I realize moving to 40b will make things much stronger immediately, but 20b hasn't been unsuccessful. We've averaged a promotion every 2 days it seems like since the switch (7 promotions in about 15 days) and had multiple non-promotions between 50%-55%.

**Comment by jkiliani** [comment] 2018-08-16 12:47
The new training cycle is shown on the tooltip and graph as having the same number of training games as the previous one. Is there an error in the graph/tooltip, or did recent self-play games not get parsed for some reason?

**Comment by alphaladder** [comment] 2018-08-17 03:12
@roy7 could you mind let us know the standard of sucessful 20b? Exceed elf , reach the ceiling of 20b, test running for quick 40b. Thanks.

**Comment by bubblesld** [comment] 2018-08-17 05:41
I think that we can train both 20b and 40b simultaneously. The question is what kind of self-games we should  generate? If the self-games generated by 40b have much better quality, it might be more efficient to spend time x2 to do it (this is probably what @gcp wanted to express? ) . For 20b training, it may progress better with 40b games. However, it may be saver to have its own self-games. How about something like generating 40b and 20b in the ratio of 3:1 (or other number?)

**Comment by alphaladder** [comment] 2018-08-17 05:56
@roy7 @bjiyxo @gcp Our colab  trainers is testing to backup  the 40b and 20b weights to some other cloud storages to decrease the traffic issue , and it works well today with everyone ‘s effort.

I have no personal bias on 20b or 40b. The strong motivation for 40b is just to linear our traning resource efficiently. Technically, 40b games is more valuable than that of 20b in the same training cycles, which is also confirmed by some professional players.

I think starting  1-2 cycles of 40b training test is very good option ,which may calm down all the boring discussion on block promotion recently. At least ,we could onbtain reliable data other than hypothesis.

**Comment by diadorak** [comment] 2018-08-18 02:10
I guess @gcp wants to first make the quantized network method work before  moving to 40b to minimize the stress on the server? Otherwise it seems training the 20b is kind of inefficient at least?

**Comment by bash99** [comment] 2018-08-21 08:15
a304 vs 8893  (168)   85% win rate
e2be vs 6774（162）82% win rate
a304 vs e2be 50.57%，both are 40b

so does there have some real progress between 168 and 162?

**Comment by Marcin1960** [comment] 2018-08-21 09:53
Here is a small utility that shows chances for two equal strength nets to get a certain winrate.

[NetChance.zip](https://github.com/gcp/leela-zero/files/2305765/NetChance.zip)


It shows that while 400 matches indeed need 55% threshold, 1200 matches will do even better at 53%.
At 100 matches 59% should be required.


NetChance.exe 400 10000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 32.85%  19.92%  11.23%  06.51%  02.70%  01.03%  00.30%  00.06%  00.01%
(random deviation from the middle: 0.0000675%)


NetChance.exe 1200 10000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 24.48%  08.32%  02.07%  00.20%  00.00%  00.00%  00.00%  00.00%  00.00%
(random deviation from the middle: -0.0000045%)


NetChance.exe 100 10000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 39.00%  31.56%  24.85%  24.85%  18.82%  13.52%  06.66%  04.45%  02.86%
(random deviation from the middle: 0.0003880%)

**Comment by ashinpan** [comment] 2018-08-21 12:34
@Marcin1960 Can you give us the link to the code of NetChance? I, for one, am a Linux user, so cannot use the exe file.

**Comment by Marcin1960** [comment] 2018-08-21 12:57
@ashinpan 

It is messy, but here you are:

[NetChanceCpp.zip](https://github.com/gcp/leela-zero/files/2306319/NetChanceCpp.zip)

**Comment by ashinpan** [comment] 2018-08-21 13:18
@Marcin1960 Thanks a lot.

**Comment by l1t1** [comment] 2018-08-21 13:35
@bash99
a benchmark like elfv0 is needed to judge that

**Comment by l1t1** [comment] 2018-08-24 06:33
@Marcin1960 
how to explain following result?
```
D:\>g++ -O3 NetChance.cpp -o NetChance.exe

D:\>NetChance 400 50000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 32.73%  19.99%  11.24%  06.40%  02.73%  01.05%  00.28%  00.06%  00.01%
(random deviation from the middle: 0.0000244%)


D:\>NetChance 410 50000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 32.73%  20.24%  11.53%  05.52%  02.26%  00.94%  00.36%  00.07%  00.00%
(random deviation from the middle: 0.0000135%)


D:\>NetChance 420 50000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 32.93%  20.33%  11.89%  05.75%  02.39%  00.79%  00.30%  00.04%  00.00%
(random deviation from the middle: -0.0000070%)


D:\>NetChance 430 50000

 51%     52%     53%     54%     55%     56%     57%     58%     59%
-----------------------------------------------------------------------
 33.18%  20.66%  12.25%  04.85%  02.01%  00.84%  00.24%  00.03%  00.00%
(random deviation from the middle: -0.0000018%)

I replaced #include "stdafx.h"  with #include <cstdio>

```

**Comment by l1t1** [comment] 2018-08-24 06:54
e4466f1c passed, nice

**Comment by WYVYW** [comment] 2018-08-24 17:31
We use(d) 20blocks Elf to improve 15 blocks Leela. 
Would it make sense to use 40 blocks byixo games to improve the 20blocks leela?

**Closed** 2018-09-09 10:55 UTC
